import type { Claim, DataQualityIssue, EvidenceReview, Source, SourceDocument } from "@/lib/domain/types";

import { confidence, type SeedContext } from "./context";
import {
  CLAIMS,
  DQ_ISSUES,
  EVIDENCE_REVIEWS,
  ORGANISMS,
  ORGS,
  PRICES,
  PRODUCTS,
  SKUS,
  SOURCES,
  SOURCE_DOCUMENTS,
  STANDARDS,
  TENDER,
  USERS,
} from "./ids";
import type { DemoDatasetSlices } from "./types";

/**
 * Evidence layer fixtures: sources (catalogues, quotations, tender dossier,
 * field notes), atomic claims with a spread of evidence states, the review
 * history behind the analyst-reviewed claims, and open data-quality issues.
 *
 * Governance: no claim is ever seeded above `analyst_reviewed`; price-bearing
 * claims stay at `source_captured` or below.
 */
export function seedEvidence(ctx: SeedContext): DemoDatasetSlices {
  const sources: Source[] = [
    {
      ...ctx.canonical(SOURCES.acmeCatalogue),
      type: "manufacturer_catalogue",
      title: "Acme MicroMedia Industrial Media Catalogue 2025 (Demo)",
      publisher: "Acme MicroMedia (Demo)",
      publishedAt: ctx.daysAgo(300),
      capturedAt: ctx.dateTimeDaysAgo(280),
    },
    {
      ...ctx.canonical(SOURCES.acmeWebsite),
      type: "manufacturer_website",
      title: "Acme MicroMedia product pages snapshot (Demo)",
      publisher: "Acme MicroMedia (Demo)",
      url: "https://acme-micromedia.example.com/products",
      capturedAt: ctx.dateTimeDaysAgo(60),
    },
    {
      ...ctx.canonical(SOURCES.deltaCatalogue),
      type: "manufacturer_catalogue",
      title: "Delta BioScience Microbiology Catalogue 2025 (Demo)",
      publisher: "Delta BioScience (Demo)",
      publishedAt: ctx.daysAgo(250),
      capturedAt: ctx.dateTimeDaysAgo(230),
    },
    {
      ...ctx.canonical(SOURCES.condorCatalogue),
      type: "manufacturer_catalogue",
      title: "Condor LabWorks Instruments & Consumables Catalogue (Demo)",
      publisher: "Condor LabWorks (Demo)",
      publishedAt: ctx.daysAgo(220),
      capturedAt: ctx.dateTimeDaysAgo(210),
    },
    {
      ...ctx.canonical(SOURCES.mekongQuote),
      type: "distributor_quotation",
      title: "Mekong Lab Supply quotation Q-2026-014 (Demo)",
      publisher: "Mekong Lab Supply (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(20),
    },
    {
      ...ctx.canonical(SOURCES.mekongQuoteOld),
      type: "distributor_quotation",
      title: "Mekong Lab Supply quotation Q-2025-101 (Demo)",
      publisher: "Mekong Lab Supply (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(400),
    },
    {
      ...ctx.canonical(SOURCES.saigonQuote),
      type: "distributor_quotation",
      title: "Saigon Scientific quotation SS-778 (Demo)",
      publisher: "Saigon Scientific (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(30),
    },
    {
      ...ctx.canonical(SOURCES.internalNote),
      type: "internal_note",
      title: "Field visit notes — HCMC pharma QC labs (Demo)",
      publisher: "Nexus Demo Analyst (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(45),
    },
    {
      ...ctx.canonical(SOURCES.tenderDoc),
      type: "tender_document",
      title: "Red River Hospital tender RRH-2025-014 dossier (Demo)",
      publisher: "Red River Provincial Hospital (Demo)",
      publishedAt: ctx.daysAgo(380),
      capturedAt: ctx.dateTimeDaysAgo(375),
    },
    {
      ...ctx.canonical(SOURCES.iso11133),
      type: "standard",
      title: "ISO 11133:2014 reference copy (Demo)",
      publisher: "ISO (Demo)",
      publishedAt: "2014-07-01",
      capturedAt: ctx.dateTimeDaysAgo(500),
    },
    {
      ...ctx.canonical(SOURCES.fieldObservation),
      type: "field_observation",
      title: "Installed-base observation at Delta Pharma Plant HCMC (Demo)",
      publisher: "Nexus Demo Analyst (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(75),
    },
    {
      ...ctx.canonical(SOURCES.importRecord),
      type: "import_record",
      title: "Vietnam import records extract Q1 (Demo)",
      publisher: "Demo Customs Data Service (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(200),
    },
  ];

  const sourceDocuments: SourceDocument[] = [
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.tenderPdf),
      sourceId: SOURCES.tenderDoc,
      fileName: "rrh-2025-014-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/tenders/rrh-2025-014-demo.pdf",
      pageCount: 18,
    },
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.mekongQuotePdf),
      sourceId: SOURCES.mekongQuote,
      fileName: "q-2026-014-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/quotations/q-2026-014-demo.pdf",
      pageCount: 3,
    },
  ];

  const claims: Claim[] = [
    {
      ...ctx.canonical(CLAIMS.tsaDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsa500,
      predicate: "distributed_by",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tpDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaPlates20,
      predicate: "distributed_by",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tdDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.qcDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.qcBsub10,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaConforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.tsaAcme,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso11133,
      sourceId: SOURCES.iso11133,
      confidence: confidence(0.9),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaGptEcoli),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.tsaAcme,
      predicate: "growth_promotes",
      objectValue: ORGANISMS.ecoli,
      sourceId: SOURCES.acmeCatalogue,
      confidence: confidence(0.85),
      reviewStatus: "structurally_validated",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tpShelfLife),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaPlates20,
      predicate: "shelf_life_months",
      objectValue: 6,
      sourceId: SOURCES.acmeWebsite,
      reviewByDate: ctx.daysAgo(10),
      confidence: confidence(0.7),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsa500,
      predicate: "has_price",
      objectValue: { amount: 2_850_000, currency: "VND", supplierOrgId: ORGS.mekong },
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tdPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "has_price",
      objectValue: { amount: 98, currency: "USD", supplierOrgId: ORGS.saigon },
      sourceId: SOURCES.saigonQuote,
      reviewByDate: ctx.daysAgo(1),
      confidence: confidence(0.6),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.equivFormula),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "equivalent_formula_to",
      objectValue: SKUS.tsa500,
      sourceId: SOURCES.deltaCatalogue,
      confidence: confidence(0.55),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.naDiscontinued),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.naDeltaOld,
      predicate: "discontinued",
      objectValue: true,
      sourceId: SOURCES.deltaCatalogue,
      effectiveDate: ctx.daysAgo(150),
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.mekongAuthorized),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.mekong,
      predicate: "authorized_distributor_of",
      objectValue: ORGS.acme,
      sourceId: SOURCES.acmeCatalogue,
      confidence: confidence(0.9),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dpUsesTsa),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.deltaPharma,
      predicate: "current_user_of",
      objectValue: SKUS.tsa500,
      sourceId: SOURCES.fieldObservation,
      confidence: confidence(0.75),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dpUsesPlates),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.deltaPharma,
      predicate: "current_user_of",
      objectValue: SKUS.tsaPlates20,
      sourceId: SOURCES.fieldObservation,
      confidence: confidence(0.7),
      reviewStatus: "structurally_validated",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.emLeadTime),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.emContact20,
      predicate: "typical_lead_time_days",
      objectValue: 14,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.6),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.sdaPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.sdaPlates20,
      predicate: "has_price",
      objectValue: { amount: 980_000, currency: "VND", supplierOrgId: ORGS.saigon },
      sourceId: SOURCES.importRecord,
      reviewByDate: ctx.daysAgo(30),
      confidence: confidence(0.5),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.as100Warranty),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.airAs100,
      predicate: "warranty_months",
      objectValue: 24,
      sourceId: SOURCES.condorCatalogue,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tenderIncumbent),
      subjectEntityType: "tender",
      subjectEntityId: TENDER.tender,
      predicate: "incumbent_supplier",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.tenderDoc,
      confidence: confidence(0.85),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
  ];

  // Review history behind the analyst-reviewed claims (the review queue itself
  // is derived from claims still in unverified / source_captured /
  // structurally_validated state — see dashboardSummary).
  const evidenceReviews: EvidenceReview[] = [
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.conformsCaptured),
      claimId: CLAIMS.tsaConforms,
      reviewerId: USERS.demoAnalyst,
      fromState: "unverified",
      toState: "source_captured",
      comment: "Standard reference copy attached (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(100),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.conformsAnalyst),
      claimId: CLAIMS.tsaConforms,
      reviewerId: USERS.demoAnalyst,
      fromState: "source_captured",
      toState: "analyst_reviewed",
      comment: "Cross-checked against the TDS conformance table (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(50),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.mekongAnalyst),
      claimId: CLAIMS.mekongAuthorized,
      reviewerId: USERS.demoAnalyst,
      fromState: "unverified",
      toState: "analyst_reviewed",
      comment: "Confirmed in the manufacturer catalogue distributor list (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(60),
    },
  ];

  const dataQualityIssues: DataQualityIssue[] = [
    {
      ...ctx.canonical(DQ_ISSUES.duplicatePair),
      kind: "possible_duplicate",
      entityType: "organization",
      entityId: ORGS.mekong,
      description: "Near-duplicate of 'MeKong Laboratory Supply Co. (Demo)' — triage in the entity-resolution queue.",
      severity: "medium",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.stalePrice),
      kind: "stale_evidence",
      entityType: "price_observation",
      entityId: PRICES.sdaStale,
      description: "Latest price observation for this SKU is older than 180 days (Demo).",
      severity: "low",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.missingWebsite),
      kind: "missing_field",
      entityType: "organization",
      entityId: ORGS.anGiangFoods,
      field: "website",
      description: "No website captured for this organization (Demo).",
      severity: "low",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.missingGtin),
      kind: "missing_field",
      entityType: "sku",
      entityId: SKUS.pc50,
      field: "gtin",
      description: "No GTIN captured for this instrument SKU (Demo).",
      severity: "low",
      status: "acknowledged",
    },
  ];

  return {
    source: sources,
    source_document: sourceDocuments,
    claim: claims,
    evidence_review: evidenceReviews,
    data_quality_issue: dataQualityIssues,
  };
}
