import type { Claim, DataQualityIssue, EvidenceReview, Source, SourceDocument } from "@/lib/domain/types";

import { confidence, type SeedContext } from "./context";
import {
  CLAIMS,
  DQ_ISSUES,
  EVIDENCE_REVIEWS,
  ORGANISMS,
  ORGS,
  PRICES,
  PRODUCTS,
  SKUS,
  SOURCES,
  SOURCE_DOCUMENTS,
  STANDARDS,
  TENDER,
  USERS,
} from "./ids";
import type { DemoDatasetSlices } from "./types";

/**
 * Evidence layer fixtures: sources (catalogues, quotations, tender dossier,
 * field notes), atomic claims with a spread of evidence states, the review
 * history behind the analyst-reviewed claims, and open data-quality issues.
 *
 * Governance: no claim is ever seeded above `analyst_reviewed`; price-bearing
 * claims stay at `source_captured` or below.
 */
export function seedEvidence(ctx: SeedContext): DemoDatasetSlices {
  const sources: Source[] = [
    {
      ...ctx.canonical(SOURCES.acmeCatalogue),
      type: "manufacturer_catalogue",
      title: "Acme MicroMedia Industrial Media Catalogue 2025 (Demo)",
      publisher: "Acme MicroMedia (Demo)",
      publishedAt: ctx.daysAgo(300),
      capturedAt: ctx.dateTimeDaysAgo(280),
    },
    {
      ...ctx.canonical(SOURCES.acmeWebsite),
      type: "manufacturer_website",
      title: "Acme MicroMedia product pages snapshot (Demo)",
      publisher: "Acme MicroMedia (Demo)",
      url: "https://acme-micromedia.example.com/products",
      capturedAt: ctx.dateTimeDaysAgo(60),
    },
    {
      ...ctx.canonical(SOURCES.deltaCatalogue),
      type: "manufacturer_catalogue",
      title: "Delta BioScience Microbiology Catalogue 2025 (Demo)",
      publisher: "Delta BioScience (Demo)",
      publishedAt: ctx.daysAgo(250),
      capturedAt: ctx.dateTimeDaysAgo(230),
    },
    {
      ...ctx.canonical(SOURCES.condorCatalogue),
      type: "manufacturer_catalogue",
      title: "Condor LabWorks Instruments & Consumables Catalogue (Demo)",
      publisher: "Condor LabWorks (Demo)",
      publishedAt: ctx.daysAgo(220),
      capturedAt: ctx.dateTimeDaysAgo(210),
    },
    {
      ...ctx.canonical(SOURCES.mekongQuote),
      type: "distributor_quotation",
      title: "Mekong Lab Supply quotation Q-2026-014 (Demo)",
      publisher: "Mekong Lab Supply (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(20),
    },
    {
      ...ctx.canonical(SOURCES.mekongQuoteOld),
      type: "distributor_quotation",
      title: "Mekong Lab Supply quotation Q-2025-101 (Demo)",
      publisher: "Mekong Lab Supply (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(400),
    },
    {
      ...ctx.canonical(SOURCES.saigonQuote),
      type: "distributor_quotation",
      title: "Saigon Scientific quotation SS-778 (Demo)",
      publisher: "Saigon Scientific (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(30),
    },
    {
      ...ctx.canonical(SOURCES.internalNote),
      type: "internal_note",
      title: "Field visit notes — HCMC pharma QC labs (Demo)",
      publisher: "Nexus Demo Analyst (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(45),
    },
    {
      ...ctx.canonical(SOURCES.tenderDoc),
      type: "tender_document",
      title: "Red River Hospital tender RRH-2025-014 dossier (Demo)",
      publisher: "Red River Provincial Hospital (Demo)",
      publishedAt: ctx.daysAgo(380),
      capturedAt: ctx.dateTimeDaysAgo(375),
    },
    {
      ...ctx.canonical(SOURCES.iso11133),
      type: "standard",
      title: "ISO 11133:2014 reference copy (Demo)",
      publisher: "ISO (Demo)",
      publishedAt: "2014-07-01",
      capturedAt: ctx.dateTimeDaysAgo(500),
    },
    {
      ...ctx.canonical(SOURCES.fieldObservation),
      type: "field_observation",
      title: "Installed-base observation at Delta Pharma Plant HCMC (Demo)",
      publisher: "Nexus Demo Analyst (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(75),
    },
    {
      ...ctx.canonical(SOURCES.importRecord),
      type: "import_record",
      title: "Vietnam import records extract Q1 (Demo)",
      publisher: "Demo Customs Data Service (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(200),
    },
    {
      ...ctx.canonical(SOURCES.auroraCatalogue),
      type: "manufacturer_catalogue",
      title: "Aurora BioWorks Chromogenic Media Catalogue 2026 (Demo)",
      publisher: "Aurora BioWorks (Demo)",
      publishedAt: ctx.daysAgo(120),
      capturedAt: ctx.dateTimeDaysAgo(110),
    },
    {
      ...ctx.canonical(SOURCES.hongHaQuote),
      type: "distributor_quotation",
      title: "Hong Ha Scientific quotation HH-2026-042 (Demo)",
      publisher: "Hong Ha Scientific (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(25),
    },
    {
      ...ctx.canonical(SOURCES.nfsTenderDoc),
      type: "tender_document",
      title: "Northern Food Safety Center tender NFS-2026-007 dossier (Demo)",
      publisher: "Northern Food Safety Center (Demo)",
      publishedAt: ctx.daysAgo(15),
      capturedAt: ctx.dateTimeDaysAgo(14),
    },
    {
      ...ctx.canonical(SOURCES.meridianCatalogue),
      type: "manufacturer_catalogue",
      title: "Meridian Lab Systems SteriPump Catalogue 2026 (Demo)",
      publisher: "Meridian Lab Systems (Demo)",
      publishedAt: ctx.daysAgo(140),
      capturedAt: ctx.dateTimeDaysAgo(130),
    },
    {
      ...ctx.canonical(SOURCES.saigonQuote2),
      type: "distributor_quotation",
      title: "Saigon Scientific quotation SS-802 (Demo)",
      publisher: "Saigon Scientific (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(22),
    },
    {
      ...ctx.canonical(SOURCES.novaraCatalogue),
      type: "manufacturer_catalogue",
      title: "Novara Bioprocess Cell Culture & Buffers Catalogue 2026 (Demo)",
      publisher: "Novara Bioprocess (Demo)",
      publishedAt: ctx.daysAgo(160),
      capturedAt: ctx.dateTimeDaysAgo(150),
    },
    {
      ...ctx.canonical(SOURCES.kestrelCatalogue),
      type: "manufacturer_catalogue",
      title: "Kestrel Filtration Process Filtration Catalogue 2026 (Demo)",
      publisher: "Kestrel Filtration (Demo)",
      publishedAt: ctx.daysAgo(150),
      capturedAt: ctx.dateTimeDaysAgo(140),
    },
    {
      ...ctx.canonical(SOURCES.aurigaCatalogue),
      type: "manufacturer_catalogue",
      title: "Auriga Separations Chromatography & TFF Catalogue 2026 (Demo)",
      publisher: "Auriga Separations (Demo)",
      publishedAt: ctx.daysAgo(170),
      capturedAt: ctx.dateTimeDaysAgo(160),
    },
    {
      ...ctx.canonical(SOURCES.vestaCatalogue),
      type: "manufacturer_catalogue",
      title: "Vesta Chemicals High-Purity Solvents Catalogue 2026 (Demo)",
      publisher: "Vesta Chemicals (Demo)",
      publishedAt: ctx.daysAgo(180),
      capturedAt: ctx.dateTimeDaysAgo(170),
    },
    {
      ...ctx.canonical(SOURCES.orizonCatalogue),
      type: "manufacturer_catalogue",
      title: "Orizon BioAnalytics Endotoxin Testing Catalogue 2026 (Demo)",
      publisher: "Orizon BioAnalytics (Demo)",
      publishedAt: ctx.daysAgo(130),
      capturedAt: ctx.dateTimeDaysAgo(120),
    },
    {
      ...ctx.canonical(SOURCES.hongHaQuote2),
      type: "distributor_quotation",
      title: "Hong Ha Scientific quotation HH-2026-058 (Demo)",
      publisher: "Hong Ha Scientific (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(18),
    },
    {
      ...ctx.canonical(SOURCES.mekongQuote2),
      type: "distributor_quotation",
      title: "Mekong Lab Supply quotation Q-2026-031 (Demo)",
      publisher: "Mekong Lab Supply (Demo)",
      capturedAt: ctx.dateTimeDaysAgo(16),
    },
    {
      ...ctx.canonical(SOURCES.rrh3TenderDoc),
      type: "tender_document",
      title: "Red River Hospital tender RRH-2026-003 dossier (Demo)",
      publisher: "Red River Provincial Hospital (Demo)",
      publishedAt: ctx.daysAgo(55),
      capturedAt: ctx.dateTimeDaysAgo(54),
    },
  ];

  const sourceDocuments: SourceDocument[] = [
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.tenderPdf),
      sourceId: SOURCES.tenderDoc,
      fileName: "rrh-2025-014-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/tenders/rrh-2025-014-demo.pdf",
      pageCount: 18,
    },
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.mekongQuotePdf),
      sourceId: SOURCES.mekongQuote,
      fileName: "q-2026-014-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/quotations/q-2026-014-demo.pdf",
      pageCount: 3,
    },
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.nfsTenderPdf),
      sourceId: SOURCES.nfsTenderDoc,
      fileName: "nfs-2026-007-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/tenders/nfs-2026-007-demo.pdf",
      pageCount: 9,
    },
    {
      ...ctx.canonical(SOURCE_DOCUMENTS.rrh3TenderPdf),
      sourceId: SOURCES.rrh3TenderDoc,
      fileName: "rrh-2026-003-demo.pdf",
      mimeType: "application/pdf",
      storagePath: "demo/tenders/rrh-2026-003-demo.pdf",
      pageCount: 12,
    },
  ];

  const claims: Claim[] = [
    {
      ...ctx.canonical(CLAIMS.tsaDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsa500,
      predicate: "distributed_by",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tpDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaPlates20,
      predicate: "distributed_by",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tdDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.qcDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.qcBsub10,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaConforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.tsaAcme,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso11133,
      sourceId: SOURCES.iso11133,
      confidence: confidence(0.9),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaGptEcoli),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.tsaAcme,
      predicate: "growth_promotes",
      objectValue: ORGANISMS.ecoli,
      sourceId: SOURCES.acmeCatalogue,
      confidence: confidence(0.85),
      reviewStatus: "structurally_validated",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tpShelfLife),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaPlates20,
      predicate: "shelf_life_months",
      objectValue: 6,
      sourceId: SOURCES.acmeWebsite,
      reviewByDate: ctx.daysAgo(10),
      confidence: confidence(0.7),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsaPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsa500,
      predicate: "has_price",
      objectValue: { amount: 2_850_000, currency: "VND", supplierOrgId: ORGS.mekong },
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tdPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "has_price",
      objectValue: { amount: 98, currency: "USD", supplierOrgId: ORGS.saigon },
      sourceId: SOURCES.saigonQuote,
      reviewByDate: ctx.daysAgo(1),
      confidence: confidence(0.6),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.equivFormula),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.tsaDelta500,
      predicate: "equivalent_formula_to",
      objectValue: SKUS.tsa500,
      sourceId: SOURCES.deltaCatalogue,
      confidence: confidence(0.55),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.naDiscontinued),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.naDeltaOld,
      predicate: "discontinued",
      objectValue: true,
      sourceId: SOURCES.deltaCatalogue,
      effectiveDate: ctx.daysAgo(150),
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.mekongAuthorized),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.mekong,
      predicate: "authorized_distributor_of",
      objectValue: ORGS.acme,
      sourceId: SOURCES.acmeCatalogue,
      confidence: confidence(0.9),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dpUsesTsa),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.deltaPharma,
      predicate: "current_user_of",
      objectValue: SKUS.tsa500,
      sourceId: SOURCES.fieldObservation,
      confidence: confidence(0.75),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dpUsesPlates),
      subjectEntityType: "organization",
      subjectEntityId: ORGS.deltaPharma,
      predicate: "current_user_of",
      objectValue: SKUS.tsaPlates20,
      sourceId: SOURCES.fieldObservation,
      confidence: confidence(0.7),
      reviewStatus: "structurally_validated",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.emLeadTime),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.emContact20,
      predicate: "typical_lead_time_days",
      objectValue: 14,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.6),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.sdaPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.sdaPlates20,
      predicate: "has_price",
      objectValue: { amount: 980_000, currency: "VND", supplierOrgId: ORGS.saigon },
      sourceId: SOURCES.importRecord,
      reviewByDate: ctx.daysAgo(30),
      confidence: confidence(0.5),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.as100Warranty),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.airAs100,
      predicate: "warranty_months",
      objectValue: 24,
      sourceId: SOURCES.condorCatalogue,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tenderIncumbent),
      subjectEntityType: "tender",
      subjectEntityId: TENDER.tender,
      predicate: "incumbent_supplier",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.tenderDoc,
      confidence: confidence(0.85),
      reviewStatus: "analyst_reviewed",
      reviewerId: USERS.demoAnalyst,
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.cc500,
      predicate: "distributed_by",
      objectValue: ORGS.hongHa,
      sourceId: SOURCES.hongHaQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccpDistributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.ccPlates20,
      predicate: "distributed_by",
      objectValue: ORGS.hongHa,
      sourceId: SOURCES.hongHaQuote,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccConforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.ccAurora,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso6579,
      sourceId: SOURCES.auroraCatalogue,
      confidence: confidence(0.5),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccListeria),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.ccPlatesAurora,
      predicate: "growth_promotes",
      objectValue: ORGANISMS.listeria,
      sourceId: SOURCES.auroraCatalogue,
      confidence: confidence(0.85),
      reviewStatus: "structurally_validated",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccPrice),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.cc500,
      predicate: "has_price",
      objectValue: { amount: 3_450_000, currency: "VND", supplierOrgId: ORGS.hongHa },
      sourceId: SOURCES.hongHaQuote,
      confidence: confidence(0.75),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ccpShelfLife),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.ccPlates20,
      predicate: "shelf_life_months",
      objectValue: 4,
      sourceId: SOURCES.auroraCatalogue,
      reviewByDate: ctx.daysAhead(60),
      confidence: confidence(0.7),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.st200Distributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.st200,
      predicate: "distributed_by",
      objectValue: ORGS.mekong,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.sp3000Distributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.sp3000,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.st200Price),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.st200,
      predicate: "has_price",
      objectValue: { amount: 185_000_000, currency: "VND", supplierOrgId: ORGS.mekong },
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.75),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.sp3000Conforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.sp3000Meridian,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.usp71,
      sourceId: SOURCES.meridianCatalogue,
      confidence: confidence(0.5),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.ag90Distributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.ag90,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.pc90Distributed),
      subjectEntityType: "sku",
      subjectEntityId: SKUS.pc90,
      predicate: "distributed_by",
      objectValue: ORGS.saigon,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.8),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.biGstConforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.biDelta,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso11138,
      sourceId: SOURCES.deltaCatalogue,
      confidence: confidence(0.85),
      reviewStatus: "source_captured",
      contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.biAmpConforms),
      subjectEntityType: "product",
      subjectEntityId: PRODUCTS.biSteriSure,
      predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso11138,
      sourceId: SOURCES.meridianCatalogue,
      confidence: confidence(0.5),
      reviewStatus: "unverified",
      contradictingClaimIds: [],
    },
    // -- Upstream → downstream → QC distribution claims ---------------------------
    {
      ...ctx.canonical(CLAIMS.choMaxDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.choMax10, predicate: "distributed_by",
      objectValue: ORGS.hongHa, sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.feedDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.feed1l, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.etohDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.etoh20l, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.pbsDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.pbs5l, predicate: "distributed_by",
      objectValue: ORGS.hongHa, sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.proaDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.proa1l, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.qmemDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.qmem10, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.steriFlowDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.steriFlow3, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tffDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.tff30k, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.75),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.endoZymeDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.endoZyme192, predicate: "distributed_by",
      objectValue: ORGS.hongHa, sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.lalDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.lalCart50, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.endoZymeConforms),
      subjectEntityType: "product", subjectEntityId: PRODUCTS.endoZymeOrizon, predicate: "conforms_to_standard",
      objectValue: STANDARDS.usp85, sourceId: SOURCES.orizonCatalogue, confidence: confidence(0.85),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.lalConforms),
      subjectEntityType: "product", subjectEntityId: PRODUCTS.lalDelta, predicate: "conforms_to_standard",
      objectValue: STANDARDS.usp85, sourceId: SOURCES.deltaCatalogue, confidence: confidence(0.9),
      reviewStatus: "analyst_reviewed", reviewerId: USERS.demoAnalyst, contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.etohUspGrade),
      subjectEntityType: "sku", subjectEntityId: SKUS.etoh20l, predicate: "grade",
      objectValue: "USP", sourceId: SOURCES.vestaCatalogue, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.spCanDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.spCan10, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dcpDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.dcp20, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.qcEcoliDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.qcEcoli10, predicate: "distributed_by",
      objectValue: ORGS.hongHa, sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.loopsDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.loops1000, predicate: "distributed_by",
      objectValue: ORGS.saigon, sourceId: SOURCES.saigonQuote2, confidence: confidence(0.75),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.turntableDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.turntable, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.dcpConforms),
      subjectEntityType: "product", subjectEntityId: PRODUCTS.dcpDelta, predicate: "conforms_to_standard",
      objectValue: STANDARDS.iso11133, sourceId: SOURCES.deltaCatalogue, confidence: confidence(0.85),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsa100Distributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.tsa100, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.tsa5kgDistributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.tsa5kg, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.choMax100Distributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.choMax100, predicate: "distributed_by",
      objectValue: ORGS.hongHa, sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
    {
      ...ctx.canonical(CLAIMS.steriCan50Distributed),
      subjectEntityType: "sku", subjectEntityId: SKUS.steriCan50, predicate: "distributed_by",
      objectValue: ORGS.mekong, sourceId: SOURCES.mekongQuote2, confidence: confidence(0.8),
      reviewStatus: "source_captured", contradictingClaimIds: [],
    },
  ];

  // Review history behind the analyst-reviewed claims (the review queue itself
  // is derived from claims still in unverified / source_captured /
  // structurally_validated state — see dashboardSummary).
  const evidenceReviews: EvidenceReview[] = [
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.conformsCaptured),
      claimId: CLAIMS.tsaConforms,
      reviewerId: USERS.demoAnalyst,
      fromState: "unverified",
      toState: "source_captured",
      comment: "Standard reference copy attached (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(100),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.conformsAnalyst),
      claimId: CLAIMS.tsaConforms,
      reviewerId: USERS.demoAnalyst,
      fromState: "source_captured",
      toState: "analyst_reviewed",
      comment: "Cross-checked against the TDS conformance table (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(50),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.mekongAnalyst),
      claimId: CLAIMS.mekongAuthorized,
      reviewerId: USERS.demoAnalyst,
      fromState: "unverified",
      toState: "analyst_reviewed",
      comment: "Confirmed in the manufacturer catalogue distributor list (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(60),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.lalAnalyst),
      claimId: CLAIMS.lalConforms,
      reviewerId: USERS.demoAnalyst,
      fromState: "source_captured",
      toState: "analyst_reviewed",
      comment: "Gel-clot cartridges cross-checked against the USP <85> compendial method (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(15),
    },
    {
      ...ctx.canonical(EVIDENCE_REVIEWS.tenderAnalyst),
      claimId: CLAIMS.tenderIncumbent,
      reviewerId: USERS.demoAnalyst,
      fromState: "unverified",
      toState: "analyst_reviewed",
      comment: "Incumbency confirmed in the award section of the tender dossier (Demo).",
      reviewedAt: ctx.dateTimeDaysAgo(90),
    },
  ];

  const dataQualityIssues: DataQualityIssue[] = [
    {
      ...ctx.canonical(DQ_ISSUES.duplicatePair),
      kind: "possible_duplicate",
      entityType: "organization",
      entityId: ORGS.mekong,
      description: "Near-duplicate of 'MeKong Laboratory Supply Co. (Demo)' — triage in the entity-resolution queue.",
      severity: "medium",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.stalePrice),
      kind: "stale_evidence",
      entityType: "price_observation",
      entityId: PRICES.sdaStale,
      description: "Latest price observation for this SKU is older than 180 days (Demo).",
      severity: "low",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.missingWebsite),
      kind: "missing_field",
      entityType: "organization",
      entityId: ORGS.anGiangFoods,
      field: "website",
      description: "No website captured for this organization (Demo).",
      severity: "low",
      status: "open",
    },
    {
      ...ctx.canonical(DQ_ISSUES.missingGtin),
      kind: "missing_field",
      entityType: "sku",
      entityId: SKUS.pc50,
      field: "gtin",
      description: "No GTIN captured for this instrument SKU (Demo).",
      severity: "low",
      status: "acknowledged",
    },
    {
      ...ctx.canonical(DQ_ISSUES.missingGtinAg90),
      kind: "missing_field",
      entityType: "sku",
      entityId: SKUS.ag90,
      field: "gtin",
      description: "No GTIN captured for this instrument SKU (Demo).",
      severity: "low",
      status: "open",
    },
  ];

  return {
    source: sources,
    source_document: sourceDocuments,
    claim: claims,
    evidence_review: evidenceReviews,
    data_quality_issue: dataQualityIssues,
  };
}
