/**
 * Stable, human-readable ids for every seeded demo record. Centralized so the
 * modular seed files can cross-link records without import cycles.
 *
 * Ids are slug-like (`org-acme-micromedia`) on purpose: demo data should be
 * easy to recognize in the UI, in tests and in signal explanations.
 */

export const DEMO_TENANT_ID = "tenant_demo";
export const OTHER_TENANT_ID = "tenant_other";

export const USERS = {
  demoOwner: "user_demo_owner",
  demoAnalyst: "user_demo_analyst",
  demoViewer: "user_demo_viewer",
  otherOwner: "user_other_owner",
} as const;

export const ORGS = {
  acme: "org-acme-micromedia",
  deltaBio: "org-delta-bioscience",
  condor: "org-condor-labworks",
  mekong: "org-mekong-lab-supply",
  mekongDup: "org-mekong-laboratory-supply",
  saigon: "org-saigon-scientific",
  deltaPharma: "org-delta-pharma-hcmc",
  anGiangFoods: "org-an-giang-foods",
  mekongContractLabs: "org-mekong-contract-labs",
  redRiverHospital: "org-red-river-hospital",
  aurora: "org-aurora-bioworks",
  hongHa: "org-hong-ha-scientific",
  songHuong: "org-song-huong-dairy",
  nfsCenter: "org-nfs-center",
  meridian: "org-meridian-lab-systems",
  novara: "org-novara-bioprocess",
  kestrel: "org-kestrel-filtration",
  auriga: "org-auriga-separations",
  vesta: "org-vesta-chemicals",
  orizon: "org-orizon-bioanalytics",
  picosep: "org-picosep-analytics",
} as const;

export const ADDRESSES = {
  mekong: "addr-mekong-thu-duc",
  mekongDup: "addr-mekong-dup-thu-duc",
  saigon: "addr-saigon-hcmc",
  deltaPharma: "addr-delta-pharma-binh-chanh",
  anGiang: "addr-an-giang-long-xuyen",
  contractLabs: "addr-mekong-contract-labs-can-tho",
  redRiver: "addr-red-river-ha-noi",
  hongHa: "addr-hong-ha-ha-noi",
  songHuong: "addr-song-huong-hue",
  nfs: "addr-nfs-ha-noi",
} as const;

export const SITES = {
  deltaPharmaPlant: "site-delta-pharma-plant",
  mekongOffice: "site-mekong-office",
  mekongDupWarehouse: "site-mekong-dup-warehouse",
  saigonOffice: "site-saigon-office",
  redRiverMain: "site-red-river-main",
  anGiangPlant: "site-an-giang-plant",
  contractLabsSite: "site-mekong-contract-labs-site",
  hongHaOffice: "site-hong-ha-office",
  songHuongPlant: "site-song-huong-plant",
  nfsSite: "site-nfs-site",
} as const;

export const LABS = {
  deltaPharmaMicro: "lab-delta-pharma-micro",
  redRiverMicro: "lab-red-river-micro",
  songHuongMicro: "lab-song-huong-micro",
} as const;

export const PEOPLE = {
  nguyenVanAn: "person-nguyen-van-an",
  tranThiBinh: "person-tran-thi-binh",
  /** Deliberate tenant_other record for isolation tests. */
  phamThiLan: "person-pham-thi-lan",
  leThiHoa: "person-le-thi-hoa",
  daoVanMinh: "person-dao-van-minh",
  nguyenThiMai: "person-nguyen-thi-mai",
} as const;

export const BRANDS = {
  acmeMedia: "brand-acme-media",
  deltaBio: "brand-deltabio",
  condorAir: "brand-condor-air",
  condorSteri: "brand-condor-steri",
  auroraChrom: "brand-aurorachrom",
  steripump: "brand-steripump",
  meridianAir: "brand-meridian-air",
  steriSure: "brand-sterisure",
  novaraCell: "brand-novaracell",
  kestrelFlow: "brand-kestrelflow",
  auriSelect: "brand-auriselect",
  vestaPure: "brand-vestapure",
  orizonEndo: "brand-orizonendo",
  orizonQc: "brand-orizonqc",
  picosep: "brand-picosep",
  auriSep: "brand-aurisep",
  vestaRef: "brand-vestaref",
} as const;

export const FAMILIES = {
  acmeDehydra: "fam-acme-dehydra",
  acmePlates: "fam-acme-plates",
  deltaMedia: "fam-delta-media",
  deltaPlates: "fam-delta-plates",
  deltaQc: "fam-delta-qc",
  condorAir: "fam-condor-air",
  condorEm: "fam-condor-em",
  condorCount: "fam-condor-count",
  condorSteri: "fam-condor-steri",
  auroraChrom: "fam-aurorachrom",
  auroraPlates: "fam-aurora-plates",
  condorSteriPump: "fam-condor-steripump",
  steripump: "fam-steripump",
  meridianAir: "fam-meridian-air",
  meridianCount: "fam-meridian-count",
  deltaBi: "fam-delta-bi",
  steriSureBi: "fam-sterisure-bi",
  choMax: "fam-novara-chomax",
  deltaGrow: "fam-delta-grow",
  vestaSolvents: "fam-vesta-solvents",
  novaraBuffers: "fam-novara-buffers",
  auriSelectResin: "fam-auriselect-resin",
  kestrelMembrane: "fam-kestrel-membrane",
  kestrelSteriFlow: "fam-kestrel-steriflow",
  auriFlow: "fam-auriflow-tff",
  endoZyme: "fam-orizon-endozyme",
  deltaTest: "fam-delta-test-lal",
  spCan: "fam-steripump-canisters",
  deltaEm: "fam-delta-em",
  orizonQc: "fam-orizon-qc",
  condorAccessories: "fam-condor-accessories",
  meridianAccessories: "fam-meridian-accessories",
  picosepCols: "fam-picosep-columns",
  auriSepCols: "fam-aurisep-columns",
  vestaRef: "fam-vesta-ref",
  orizonRef: "fam-orizon-ref",
  auroraWater: "fam-aurora-water",
  deltaWater: "fam-delta-water",
  novaraFlex: "fam-novaraflex",
  kestrelFlex: "fam-kestrelflex",
} as const;

export const PRODUCTS = {
  tsaAcme: "prod-tsa-acme",
  tsaPlatesAcme: "prod-tsa-plates-acme",
  nbAcme: "prod-nb-acme",
  tsaDelta: "prod-tsa-delta",
  sdaPlatesDelta: "prod-sda-plates-delta",
  qcDelta: "prod-qc-delta",
  naDeltaOld: "prod-na-delta-old",
  naDelta: "prod-na-delta",
  airCondor: "prod-air-condor",
  emCondor: "prod-em-condor",
  pcCondor: "prod-pc-condor",
  steriCondor: "prod-steri-condor",
  ccAurora: "prod-cc-aurora",
  ccPlatesAurora: "prod-cc-plates-aurora",
  st200Condor: "prod-st200-condor",
  sp3000Meridian: "prod-sp3000-meridian",
  ag90Meridian: "prod-ag90-meridian",
  pc90Meridian: "prod-pc90-meridian",
  biDelta: "prod-bi-delta",
  biSteriSure: "prod-bi-sterisure",
  choMaxNovara: "prod-chomax-novara",
  feedDelta: "prod-feed-delta",
  etohVesta: "prod-etoh-vesta",
  pbsNovara: "prod-pbs-novara",
  proaAuriga: "prod-proa-auriga",
  qKestrel: "prod-qmem-kestrel",
  steriFlowKestrel: "prod-steriflow-kestrel",
  tffAuriga: "prod-tff-auriga",
  endoZymeOrizon: "prod-endozyme-orizon",
  lalDelta: "prod-lal-delta",
  spCanMeridian: "prod-spcan-meridian",
  dcpDelta: "prod-dcp-delta",
  qcEcoliOrizon: "prod-qc-ecoli-orizon",
  turntableCondor: "prod-turntable-condor",
  loopsMeridian: "prod-loops-meridian",
  c18PicoSep: "prod-c18-picosep",
  c18AuriSep: "prod-c18-aurisep",
  rsVesta: "prod-rs-vesta",
  cseOrizon: "prod-cse-orizon",
  waterAurora: "prod-water-aurora",
  waterDelta: "prod-water-delta",
  subNovara: "prod-sub-novara",
  sumKestrel: "prod-sum-kestrel",
  st300Condor: "prod-st300-condor",
  sp1000Meridian: "prod-sp1000-meridian",
} as const;

export const SKUS = {
  tsa500: "sku-tsa-500",
  /** Import-created near-duplicate of tsa500 (same catalogue number). */
  tsa500Dup: "sku-tsa-500-dup",
  tsaPlates20: "sku-tsa-plates-20",
  nb500: "sku-nb-500",
  tsaDelta500: "sku-tsa-delta-500",
  sdaPlates20: "sku-sda-plates-20",
  qcBsub10: "sku-qc-bsub-10",
  naOld500: "sku-na-old-500",
  na2x500: "sku-na2-500",
  airAs100: "sku-air-as100",
  emContact20: "sku-em-contact-20",
  pc50: "sku-pc50",
  steriCan10: "sku-steri-can-10",
  cc500: "sku-cc-500",
  ccPlates20: "sku-cc-plates-20",
  st200: "sku-st200",
  sp3000: "sku-sp3000",
  ag90: "sku-ag90",
  pc90: "sku-pc90",
  biGst100: "sku-bi-gst-100",
  biAmp20: "sku-bi-amp-20",
  choMax10: "sku-chomax-10",
  feed1l: "sku-feed-1l",
  etoh20l: "sku-etoh-20l",
  pbs5l: "sku-pbs-5l",
  proa1l: "sku-proa-1l",
  qmem10: "sku-qmem-10",
  steriFlow3: "sku-steriflow-3",
  tff30k: "sku-tff-30k",
  endoZyme192: "sku-endozyme-192",
  lalCart50: "sku-lal-cart-50",
  spCan10: "sku-spcan-10",
  dcp20: "sku-dcp-20",
  qcEcoli10: "sku-qc-ecoli-10",
  turntable: "sku-turntable",
  loops1000: "sku-loops-1000",
  tsa100: "sku-tsa-100",
  tsa5kg: "sku-tsa-5kg",
  choMax100: "sku-chomax-100",
  steriCan50: "sku-steri-can-50",
  c18ps21: "sku-c18ps-21",
  c18as46: "sku-c18as-46",
  rsAcet: "sku-rs-acet",
  cse10: "sku-cse-10",
  waterPa100: "sku-water-pa-100",
  waterMf50: "sku-water-mf-50",
  sub50: "sku-sub-50",
  sum100: "sku-sum-100",
  st300: "sku-st300",
  sp1000: "sku-sp1000",
} as const;

export const PACKS = {
  tsa500: "pack-tsa-500",
  tsaPlates20: "pack-tsa-plates-20",
  nb500: "pack-nb-500",
  tsaDelta500: "pack-tsa-delta-500",
  sda20: "pack-sda-20",
  qcBsub10: "pack-qc-bsub-10",
  na2x500: "pack-na2-500",
  emContact20: "pack-em-contact-20",
  steri10: "pack-steri-10",
  airAs100: "pack-air-as100",
  pc50: "pack-pc50",
  cc500: "pack-cc-500",
  ccPlates20: "pack-cc-plates-20",
  st200: "pack-st200",
  sp3000: "pack-sp3000",
  ag90: "pack-ag90",
  pc90: "pack-pc90",
  biGst100: "pack-bi-gst-100",
  biAmp20: "pack-bi-amp-20",
  choMax10: "pack-chomax-10",
  feed1l: "pack-feed-1l",
  etoh20l: "pack-etoh-20l",
  pbs5l: "pack-pbs-5l",
  proa1l: "pack-proa-1l",
  qmem10: "pack-qmem-10",
  steriFlow3: "pack-steriflow-3",
  tff30k: "pack-tff-30k",
  endoZyme192: "pack-endozyme-192",
  lalCart50: "pack-lal-cart-50",
  spCan10: "pack-spcan-10",
  dcp20: "pack-dcp-20",
  qcEcoli10: "pack-qc-ecoli-10",
  turntable: "pack-turntable",
  loops1000: "pack-loops-1000",
  tsa100: "pack-tsa-100",
  tsa5kg: "pack-tsa-5kg",
  choMax100: "pack-chomax-100",
  steriCan50: "pack-steri-can-50",
  c18ps21: "pack-c18ps-21",
  c18as46: "pack-c18as-46",
  rsAcet: "pack-rs-acet",
  cse10: "pack-cse-10",
  waterPa100: "pack-water-pa-100",
  waterMf50: "pack-water-mf-50",
  sub50: "pack-sub-50",
  sum100: "pack-sum-100",
  st300: "pack-st300",
  sp1000: "pack-sp1000",
} as const;

export const FORMATS = {
  granulated: "fmt-granulated",
  readyPlate: "fmt-ready-plate",
  pellet: "fmt-pellet",
  instrument: "fmt-instrument",
  canister: "fmt-canister",
} as const;

export const APPLICATIONS = {
  sterilityTesting: "app-sterility-testing",
  microbialLimits: "app-microbial-limits",
  envMonitoring: "app-environmental-monitoring",
  growthPromotion: "app-growth-promotion",
  mediaFill: "app-media-fill",
  pathogenDetection: "app-pathogen-detection",
  sterilizationValidation: "app-sterilization-validation",
  upstreamCellCulture: "app-upstream-cell-culture",
  apiSynthesis: "app-api-synthesis",
  downstreamPurification: "app-downstream-purification",
  endotoxinTesting: "app-endotoxin-testing",
  sterileFiltration: "app-sterile-filtration",
  analyticalQc: "app-analytical-qc",
  waterQualityTesting: "app-water-quality-testing",
} as const;

export const METHODS = {
  membraneFiltration: "mth-membrane-filtration",
  plateCount: "mth-plate-count",
  affinityChromatography: "mth-affinity-chromatography",
  hplc: "mth-hplc",
} as const;

export const STANDARDS = {
  iso11133: "std-iso-11133",
  iso17025: "std-iso-17025",
  usp61: "std-usp-61",
  usp71: "std-usp-71",
  tcvnDemo: "std-tcvn-9999",
  iso6579: "std-iso-6579",
  iso11290: "std-iso-11290",
  iso11138: "std-iso-11138",
  usp85: "std-usp-85",
  usp621: "std-usp-621",
  iso9308: "std-iso-9308",
} as const;

export const STANDARD_VERSIONS = {
  iso11133v2014: "stdv-iso-11133-2014",
  iso17025v2017: "stdv-iso-17025-2017",
  usp61v2024: "stdv-usp-61-2024",
  usp71v2024: "stdv-usp-71-2024",
  tcvnV2025: "stdv-tcvn-9999-2025",
  iso6579v2017: "stdv-iso-6579-2017",
  iso11290v2017: "stdv-iso-11290-2017",
  iso11138v2017: "stdv-iso-11138-2017",
  usp85v2024: "stdv-usp-85-2024",
  usp621v2024: "stdv-usp-621-2024",
  iso9308v2014: "stdv-iso-9308-2014",
} as const;

export const ORGANISMS = {
  bsub: "orgm-bacillus-subtilis-atcc-6633",
  ecoli: "orgm-escherichia-coli-atcc-8739",
  saur: "orgm-staphylococcus-aureus-atcc-6538",
  paer: "orgm-pseudomonas-aeruginosa-atcc-9027",
  calb: "orgm-candida-albicans-atcc-10231",
  listeria: "orgm-listeria-monocytogenes-atcc-13932",
  salmonella: "orgm-salmonella-enterica-atcc-14028",
  gstearo: "orgm-geobacillus-stearothermophilus-atcc-12980",
} as const;

export const SAMPLE_TYPES = {
  water: "smp-purified-water",
  air: "smp-air",
  surface: "smp-surface-swab",
  rawMaterial: "smp-raw-material",
  milk: "smp-raw-milk",
  cellCultureBroth: "smp-cell-culture-broth",
  bulkDrugSubstance: "smp-bulk-drug-substance",
} as const;

export const INDUSTRIES = {
  pharma: "ind-pharma",
  food: "ind-food-beverage",
} as const;

export const TEST_TYPES = {
  bioburden: "tt-bioburden",
  sterilityTest: "tt-sterility-test",
  endotoxinTest: "tt-endotoxin-test",
  assayHplc: "tt-assay-hplc",
} as const;

export const INCUBATION = { aerobic3035: "inc-aerobic-30-35-3d" } as const;
export const PREPARATION = { autoclave: "prep-autoclave-121-15" } as const;

export const SOURCES = {
  acmeCatalogue: "src-acme-catalogue",
  acmeWebsite: "src-acme-website",
  deltaCatalogue: "src-delta-catalogue",
  condorCatalogue: "src-condor-catalogue",
  mekongQuote: "src-mekong-quote",
  mekongQuoteOld: "src-mekong-quote-old",
  saigonQuote: "src-saigon-quote",
  internalNote: "src-internal-note",
  tenderDoc: "src-tender-doc",
  iso11133: "src-iso-11133",
  fieldObservation: "src-field-observation",
  importRecord: "src-import-record",
  auroraCatalogue: "src-aurora-catalogue",
  hongHaQuote: "src-hongha-quote",
  nfsTenderDoc: "src-nfs-tender-doc",
  meridianCatalogue: "src-meridian-catalogue",
  saigonQuote2: "src-saigon-quote-2",
  novaraCatalogue: "src-novara-catalogue",
  kestrelCatalogue: "src-kestrel-catalogue",
  aurigaCatalogue: "src-auriga-catalogue",
  vestaCatalogue: "src-vesta-catalogue",
  orizonCatalogue: "src-orizon-catalogue",
  hongHaQuote2: "src-hongha-quote-2",
  mekongQuote2: "src-mekong-quote-2",
  rrh3TenderDoc: "src-rrh3-tender-doc",
  picosepCatalogue: "src-picosep-catalogue",
} as const;

export const SOURCE_DOCUMENTS = {
  tenderPdf: "sdoc-tender-pdf",
  mekongQuotePdf: "sdoc-mekong-quote-pdf",
  nfsTenderPdf: "sdoc-nfs-tender-pdf",
  rrh3TenderPdf: "sdoc-rrh3-tender-pdf",
} as const;

export const CLAIMS = {
  tsaDistributed: "claim-tsa-distributed",
  tpDistributed: "claim-tp-distributed",
  tdDistributed: "claim-td-distributed",
  qcDistributed: "claim-qc-distributed",
  tsaConforms: "claim-tsa-conforms",
  tsaGptEcoli: "claim-tsa-gpt-ecoli",
  tpShelfLife: "claim-tp-shelf-life",
  tsaPrice: "claim-tsa-price",
  tdPrice: "claim-td-price",
  equivFormula: "claim-equiv-formula",
  naDiscontinued: "claim-na-discontinued",
  mekongAuthorized: "claim-mekong-authorized",
  dpUsesTsa: "claim-dp-uses-tsa",
  dpUsesPlates: "claim-dp-uses-plates",
  emLeadTime: "claim-em-lead-time",
  sdaPrice: "claim-sda-price",
  as100Warranty: "claim-as100-warranty",
  tenderIncumbent: "claim-tender-incumbent",
  ccDistributed: "claim-cc-distributed",
  ccpDistributed: "claim-ccp-distributed",
  ccConforms: "claim-cc-conforms",
  ccListeria: "claim-cc-listeria",
  ccPrice: "claim-cc-price",
  ccpShelfLife: "claim-ccp-shelf-life",
  st200Distributed: "claim-st200-distributed",
  sp3000Distributed: "claim-sp3000-distributed",
  st200Price: "claim-st200-price",
  sp3000Conforms: "claim-sp3000-conforms",
  ag90Distributed: "claim-ag90-distributed",
  pc90Distributed: "claim-pc90-distributed",
  biGstConforms: "claim-bi-gst-conforms",
  biAmpConforms: "claim-bi-amp-conforms",
  choMaxDistributed: "claim-chomax-distributed",
  feedDistributed: "claim-feed-distributed",
  etohDistributed: "claim-etoh-distributed",
  pbsDistributed: "claim-pbs-distributed",
  proaDistributed: "claim-proa-distributed",
  qmemDistributed: "claim-qmem-distributed",
  steriFlowDistributed: "claim-steriflow-distributed",
  tffDistributed: "claim-tff-distributed",
  endoZymeDistributed: "claim-endozyme-distributed",
  lalDistributed: "claim-lal-distributed",
  endoZymeConforms: "claim-endozyme-conforms",
  lalConforms: "claim-lal-conforms",
  etohUspGrade: "claim-etoh-usp-grade",
  spCanDistributed: "claim-spcan-distributed",
  dcpDistributed: "claim-dcp-distributed",
  qcEcoliDistributed: "claim-qc-ecoli-distributed",
  loopsDistributed: "claim-loops-distributed",
  turntableDistributed: "claim-turntable-distributed",
  dcpConforms: "claim-dcp-conforms",
  tsa100Distributed: "claim-tsa-100-distributed",
  tsa5kgDistributed: "claim-tsa-5kg-distributed",
  choMax100Distributed: "claim-chomax-100-distributed",
  steriCan50Distributed: "claim-steri-can-50-distributed",
  c18psDistributed: "claim-c18ps-distributed",
  c18asDistributed: "claim-c18as-distributed",
  rsDistributed: "claim-rs-distributed",
  cseDistributed: "claim-cse-distributed",
  waterPaDistributed: "claim-water-pa-distributed",
  waterMfDistributed: "claim-water-mf-distributed",
  subDistributed: "claim-sub-distributed",
  sumDistributed: "claim-sum-distributed",
  c18psConforms: "claim-c18ps-conforms",
  waterPaConforms: "claim-water-pa-conforms",
  cseConforms: "claim-cse-conforms",
  st300Distributed: "claim-st300-distributed",
  sp1000Distributed: "claim-sp1000-distributed",
  st200Sp3000Equiv: "claim-st200-sp3000-equiv",
  rfcLalEquiv: "claim-rfc-lal-equiv",
} as const;

export const EVIDENCE_REVIEWS = {
  conformsCaptured: "rev-tsa-conforms-captured",
  conformsAnalyst: "rev-tsa-conforms-analyst",
  mekongAnalyst: "rev-mekong-analyst",
  lalAnalyst: "rev-lal-analyst",
  tenderAnalyst: "rev-tender-analyst",
} as const;

export const DQ_ISSUES = {
  duplicatePair: "dq-duplicate-mekong",
  stalePrice: "dq-stale-price-sda",
  missingWebsite: "dq-missing-website-an-giang",
  missingGtin: "dq-missing-gtin-pc50",
  missingGtinAg90: "dq-missing-gtin-ag90",
} as const;

export const SUPPLIER_PROFILES = {
  mekong: "supp-mekong",
  mekongDup: "supp-mekong-dup",
  saigon: "supp-saigon",
  hongHa: "supp-hongha",
} as const;

export const AGREEMENTS = {
  acmeMekong: "dagr-acme-mekong",
  deltaSaigon: "dagr-delta-saigon",
  auroraHongHa: "dagr-aurora-hongha",
} as const;

export const LISTINGS = {
  mekongTsa: "listing-mekong-tsa",
  mekongTp: "listing-mekong-tp",
  mekongNb: "listing-mekong-nb",
  mekongAir: "listing-mekong-air",
  mekongEm: "listing-mekong-em",
  mekongPc: "listing-mekong-pc",
  saigonTd: "listing-saigon-td",
  saigonSda: "listing-saigon-sda",
  saigonQc: "listing-saigon-qc",
  saigonNa2: "listing-saigon-na2",
  saigonSteri: "listing-saigon-steri",
  hongHaCc: "listing-hongha-cc",
  hongHaCcp: "listing-hongha-ccp",
  mekongSt200: "listing-mekong-st200",
  saigonSp3000: "listing-saigon-sp3000",
  saigonAg90: "listing-saigon-ag90",
  saigonPc90: "listing-saigon-pc90",
  saigonBiGst: "listing-saigon-bi-gst",
  saigonBiAmp: "listing-saigon-bi-amp",
  hongHaChoMax: "listing-hongha-chomax",
  saigonFeed: "listing-saigon-feed",
  mekongEtoh: "listing-mekong-etoh",
  hongHaPbs: "listing-hongha-pbs",
  saigonProa: "listing-saigon-proa",
  mekongQmem: "listing-mekong-qmem",
  mekongSteriFlow: "listing-mekong-steriflow",
  saigonTff: "listing-saigon-tff",
  hongHaEndoZyme: "listing-hongha-endozyme",
  saigonLal: "listing-saigon-lal",
  saigonSpCan: "listing-saigon-spcan",
  saigonDcp: "listing-saigon-dcp",
  hongHaQcEcoli: "listing-hongha-qc-ecoli",
  mekongTurntable: "listing-mekong-turntable",
  saigonLoops: "listing-saigon-loops",
  mekongTsa100: "listing-mekong-tsa-100",
  mekongTsa5kg: "listing-mekong-tsa-5kg",
  hongHaChoMax100: "listing-hongha-chomax-100",
  mekongSteriCan50: "listing-mekong-steri-can-50",
  hongHaC18ps: "listing-hongha-c18ps",
  saigonC18as: "listing-saigon-c18as",
  mekongRs: "listing-mekong-rs",
  hongHaCse: "listing-hongha-cse",
  hongHaWaterPa: "listing-hongha-water-pa",
  saigonWaterMf: "listing-saigon-water-mf",
  hongHaSub: "listing-hongha-sub",
  mekongSum: "listing-mekong-sum",
  mekongSt300: "listing-mekong-st300",
  saigonSp1000: "listing-saigon-sp1000",
} as const;

export const AVAILABILITY = {
  tsaInStock: "avail-tsa-in-stock",
  tpLimited: "avail-tp-limited",
  tpOutOfStock: "avail-tp-out-of-stock",
  sdaOutOfStock: "avail-sda-out-of-stock",
  airInStock: "avail-air-in-stock",
  emInStock: "avail-em-in-stock",
  pcInStock: "avail-pc-in-stock",
  na2InStock: "avail-na2-in-stock",
  ccInStock: "avail-cc-in-stock",
  ccpInStock: "avail-ccp-in-stock",
  st200InStock: "avail-st200-in-stock",
  sp3000Limited: "avail-sp3000-limited",
  ag90InStock: "avail-ag90-in-stock",
  pc90InStock: "avail-pc90-in-stock",
  biGstInStock: "avail-bi-gst-in-stock",
  biAmpLimited: "avail-bi-amp-limited",
  choMaxInStock: "avail-chomax-in-stock",
  feedInStock: "avail-feed-in-stock",
  etohInStock: "avail-etoh-in-stock",
  pbsLimited: "avail-pbs-limited",
  proaLimited: "avail-proa-limited",
  qmemInStock: "avail-qmem-in-stock",
  steriFlowInStock: "avail-steriflow-in-stock",
  tffInStock: "avail-tff-in-stock",
  endoZymeInStock: "avail-endozyme-in-stock",
  lalInStock: "avail-lal-in-stock",
  spCanInStock: "avail-spcan-in-stock",
  dcpInStock: "avail-dcp-in-stock",
  qcEcoliInStock: "avail-qc-ecoli-in-stock",
  turntableInStock: "avail-turntable-in-stock",
  loopsInStock: "avail-loops-in-stock",
  tsa100InStock: "avail-tsa-100-in-stock",
  tsa5kgInStock: "avail-tsa-5kg-in-stock",
  choMax100Limited: "avail-chomax-100-limited",
  steriCan50InStock: "avail-steri-can-50-in-stock",
  c18psInStock: "avail-c18ps-in-stock",
  c18asInStock: "avail-c18as-in-stock",
  rsInStock: "avail-rs-in-stock",
  cseInStock: "avail-cse-in-stock",
  waterPaInStock: "avail-water-pa-in-stock",
  waterMfLimited: "avail-water-mf-limited",
  subInStock: "avail-sub-in-stock",
  sumLimited: "avail-sum-limited",
  st300InStock: "avail-st300-in-stock",
  sp1000Limited: "avail-sp1000-limited",
} as const;

export const PRICES = {
  tsaOld: "price-tsa-old",
  tsaNew: "price-tsa-new",
  tp: "price-tp",
  nb: "price-nb",
  tdNew: "price-td-new",
  tdOld: "price-td-old",
  sdaStale: "price-sda-stale",
  qc: "price-qc",
  em: "price-em",
  ccOld: "price-cc-old",
  ccNew: "price-cc-new",
  ccp: "price-ccp",
  st200: "price-st200",
  sp3000: "price-sp3000",
  ag90: "price-ag90",
  pc90: "price-pc90",
  biGst: "price-bi-gst",
  biAmp: "price-bi-amp",
  choMax: "price-chomax",
  feed: "price-feed",
  etoh: "price-etoh",
  pbs: "price-pbs",
  proa: "price-proa",
  qmem: "price-qmem",
  steriFlow: "price-steriflow",
  tff: "price-tff",
  endoZyme: "price-endozyme",
  lal: "price-lal",
  spCan: "price-spcan",
  dcp: "price-dcp",
  qcEcoli: "price-qc-ecoli",
  turntable: "price-turntable",
  loops: "price-loops",
  tsa100: "price-tsa-100",
  tsa5kg: "price-tsa-5kg",
  choMax100: "price-chomax-100",
  steriCan50: "price-steri-can-50",
  spCanOld: "price-spcan-old",
  proaOld: "price-proa-old",
  c18ps: "price-c18ps",
  c18as: "price-c18as",
  rsAcet: "price-rs-acet",
  cse: "price-cse",
  waterPa: "price-water-pa",
  waterMf: "price-water-mf",
  sub50: "price-sub-50",
  sum100: "price-sum-100",
  st300: "price-st300",
  sp1000: "price-sp1000",
} as const;

export const PRICE_COMPONENTS = {
  qcFreight: "pcomp-qc-freight",
  sdaDuty: "pcomp-sda-duty",
} as const;

export const COMMERCIAL_TERMS = {
  mekong: "cterms-mekong",
  saigon: "cterms-saigon",
  hongHa: "cterms-hongha",
} as const;

export const TENDER = {
  tender: "tender-rrh-2025-014",
  lotMedia: "lot-rrh-media",
  lotQc: "lot-rrh-qc",
  itemTsa: "item-rrh-tsa",
  itemTsaPlates: "item-rrh-tsa-plates",
  itemQc: "item-rrh-qc",
  bidMekong: "bid-rrh-mekong",
  bidSaigon: "bid-rrh-saigon",
  awardMedia: "award-rrh-media",
  evPublished: "tev-rrh-published",
  evClarification: "tev-rrh-clarification",
  evClosed: "tev-rrh-closed",
  evAwarded: "tev-rrh-awarded",
} as const;

export const TENDER2 = {
  tender: "tender-nfs-2026-007",
  lotMedia: "lot-nfs-media",
  itemCc: "item-nfs-cc",
  itemCcp: "item-nfs-ccp",
  evPublished: "tev-nfs-published",
  evClarification: "tev-nfs-clarification",
} as const;

export const TENDER3 = {
  tender: "tender-rrh-2026-003",
  lotEndo: "lot-rrh3-endo",
  itemEndoZyme: "item-rrh3-endozyme",
  itemLal: "item-rrh3-lal",
  bidHongHa: "bid-rrh3-hongha",
  bidSaigon: "bid-rrh3-saigon",
  evPublished: "tev-rrh3-published",
  evExtended: "tev-rrh3-extended",
  evClosed: "tev-rrh3-closed",
} as const;

export const ASSET_MODELS = {
  as100: "model-airsampler-as100",
  pc50: "model-condorcount-pc50",
  ic35: "model-condor-incubator-ic35",
  st200: "model-steritest-st200",
  sp3000: "model-steripump-sp3000",
  ag90: "model-airguard-ag90",
  pc90: "model-particount-pc90",
  st300: "model-steritest-st300",
  sp1000: "model-steripump-sp1000",
} as const;

export const ASSETS = {
  as100: "asset-as100-delta-pharma",
  pc50: "asset-pc50-delta-pharma",
  ic35: "asset-ic35-song-huong",
  st200: "asset-st200-delta-pharma",
} as const;

export const ASSET_EVENTS = {
  as100Installed: "ale-as100-installed",
  pc50Installed: "ale-pc50-installed",
  as100Calibration: "maint-as100-calibration",
  as100Pq: "qual-as100-pq",
  ic35Installed: "ale-ic35-installed",
  st200Installed: "ale-st200-installed",
} as const;

export const COMPATIBILITIES = {
  as100Em: "compat-as100-em",
  as100Tp: "compat-as100-tp",
  st200Steri: "compat-st200-sterican",
  sp3000Steri: "compat-sp3000-sterican",
  sp3000SpCan: "compat-sp3000-spcan",
  ag90Tsa: "compat-ag90-tsa-plates",
  ag90Sda: "compat-ag90-sda-plates",
  st300Steri: "compat-st300-sterican",
  sp1000SpCan: "compat-sp1000-spcan",
} as const;

export const CONSUMPTION = { as100Em: "cons-as100-em" } as const;
export const REPLACEMENT_ASSUMPTIONS = { airSampler: "rass-air-sampler" } as const;

export const VENDOR_APPROVALS = {
  mekongExpired: "vappr-mekong-expired",
  saigonApproved: "vappr-saigon-approved",
  hongHaSongHuong: "vappr-hongha-songhuong",
} as const;

export const VALIDATIONS = {
  tdInProgress: "pval-td-in-progress",
  tsaPassed: "pval-tsa-passed",
  spCanPlanned: "pval-spcan-planned",
} as const;

export const TRIALS = {
  tdSample: "trial-td-sample",
  tdStarted: "trial-td-started",
} as const;

export const RESEARCH = {
  project: "rp-ready-media-vn",
  notePlates: "rnote-plates-shift",
  noteTender: "rnote-tender-bundle",
  findingFact: "rfind-fact",
  findingInterpretation: "rfind-interpretation",
  findingAssumption: "rfind-assumption",
  findingUnknown: "rfind-unknown",
  findingRecommendation: "rfind-recommendation",
  linkProduct: "rpe-product",
  linkSku: "rpe-sku",
  linkOrg: "rpe-org",
  linkTender: "rpe-tender",
  savedView: "view-ready-media-skus",
  exportPdf: "export-ready-media-pdf",
  dairyProject: "rp-dairy-pathogen-hue",
  dairyNote: "rnote-dairy-listeria",
  dairyFinding: "rfind-dairy-fact",
  dairyLinkOrg: "rpe-dairy-org",
  dairyLinkProduct: "rpe-dairy-product",
  mabProject: "rp-mab-downstream-vn",
  mabNote: "rnote-mab-resin-cogs",
  mabFinding: "rfind-mab-fact",
  mabFindingUnknown: "rfind-mab-unknown",
  mabLinkProa: "rpe-mab-proa",
  mabLinkSteriFlow: "rpe-mab-steriflow",
  mabLinkLal: "rpe-mab-lal",
  /** Deliberate tenant_other record for isolation tests. */
  otherProject: "rp-other-tenant-watch",
} as const;

export const COST_SCENARIOS = {
  tsaDehydrated: "cpt-tsa-dehydrated",
  tsaPlates: "cpt-tsa-plates",
} as const;

export const EQUIVALENCES = {
  tsaDeltaVsAcme: "equiv-tsa-delta-vs-acme",
  sdaVsTsaPlates: "equiv-sda-vs-tsa-plates",
  st200VsSp3000: "equiv-st200-vs-sp3000",
  rfcVsLal: "equiv-rfc-vs-lal",
} as const;

export const MEMBERSHIPS = {
  demoOwner: "mem-demo-owner",
  demoAnalyst: "mem-demo-analyst",
  demoViewer: "mem-demo-viewer",
  otherOwner: "mem-other-owner",
} as const;

export const PROFILES = {
  demoOwner: "profile-demo-owner",
  demoAnalyst: "profile-demo-analyst",
  demoViewer: "profile-demo-viewer",
  otherOwner: "profile-other-owner",
} as const;
