import { normalizePrice } from "@/lib/domain/price-normalization";
import type {
  AvailabilityObservation,
  CommercialTerms,
  DistributionAgreement,
  PackConfiguration,
  PriceComponent,
  PriceObservation,
  SupplierListing,
  SupplierProfile,
} from "@/lib/domain/types";

import { confidence, edgeEvidence, type SeedContext } from "./context";
import {
  AGREEMENTS,
  AVAILABILITY,
  COMMERCIAL_TERMS,
  DEMO_TENANT_ID,
  LISTINGS,
  ORGS,
  PACKS,
  PRICE_COMPONENTS,
  PRICES,
  SKUS,
  SOURCES,
  SUPPLIER_PROFILES,
} from "./ids";
import type { DemoDatasetSlices } from "./types";

/** Tests obtainable per base unit of pack content, by SKU (feeds per-test normalization). */
const YIELD_PER_UNIT: Partial<Record<string, number>> = {
  [SKUS.tsa500]: 1.25, // 500 g bottle → ~625 poured plates
  [SKUS.tsaDelta500]: 1.25,
  [SKUS.tsaPlates20]: 1, // 1 test per ready plate
  [SKUS.sdaPlates20]: 1,
  [SKUS.emContact20]: 1,
  [SKUS.cc500]: 1.25,
  [SKUS.ccPlates20]: 1,
  [SKUS.tsa100]: 1.25,
  [SKUS.tsa5kg]: 1.25,
};

/**
 * Commercial overlay fixtures: supplier profiles, distribution agreements
 * (one expired, one expiring soon), supplier listings, availability
 * observations (including a repeated stock issue), and price observations in
 * VND + USD with tax/incoterm variety and deliberate staleness.
 *
 * Price governance: every observation is synthetic (`isSynthetic: true`),
 * sourced from a Demo quotation / internal note / import extract, and never
 * reviewed above `source_captured`.
 */
export function seedPrices(ctx: SeedContext, packConfigurations: PackConfiguration[]): DemoDatasetSlices {
  const supplierProfiles: SupplierProfile[] = [
    {
      ...ctx.canonical(SUPPLIER_PROFILES.mekong),
      organizationId: ORGS.mekong,
      relationshipType: "authorized_distributor",
      manufacturers: [ORGS.acme, ORGS.condor, ORGS.kestrel, ORGS.vesta],
      countries: ["VN"],
    },
    {
      ...ctx.canonical(SUPPLIER_PROFILES.mekongDup),
      organizationId: ORGS.mekongDup,
      relationshipType: "unknown_unverified",
      manufacturers: [],
      countries: ["VN"],
    },
    {
      ...ctx.canonical(SUPPLIER_PROFILES.saigon),
      organizationId: ORGS.saigon,
      relationshipType: "non_exclusive_distributor",
      manufacturers: [ORGS.deltaBio, ORGS.meridian, ORGS.auriga],
      countries: ["VN"],
    },
    {
      ...ctx.canonical(SUPPLIER_PROFILES.hongHa),
      organizationId: ORGS.hongHa,
      relationshipType: "authorized_distributor",
      manufacturers: [ORGS.aurora, ORGS.novara, ORGS.orizon],
      countries: ["VN"],
    },
  ];

  const distributionAgreements: DistributionAgreement[] = [
    {
      // Expired ~45 days ago → supplier_agreement_expired signal.
      ...ctx.canonical(AGREEMENTS.acmeMekong),
      manufacturerOrgId: ORGS.acme,
      distributorOrgId: ORGS.mekong,
      relationshipType: "authorized_distributor",
      countries: ["VN"],
      validFrom: ctx.daysAgo(400),
      validTo: ctx.daysAgo(45),
      evidence: edgeEvidence(SOURCES.acmeCatalogue, "source_captured", 0.85),
    },
    {
      // Expires in ~60 days → counted by dashboard freshness.
      ...ctx.canonical(AGREEMENTS.deltaSaigon),
      manufacturerOrgId: ORGS.deltaBio,
      distributorOrgId: ORGS.saigon,
      relationshipType: "non_exclusive_distributor",
      countries: ["VN"],
      validFrom: ctx.daysAgo(300),
      validTo: ctx.daysAhead(60),
      evidence: edgeEvidence(SOURCES.deltaCatalogue, "source_captured", 0.8),
    },
    {
      // Healthy long-dated agreement — no signal, anchors the "all clear" case.
      ...ctx.canonical(AGREEMENTS.auroraHongHa),
      manufacturerOrgId: ORGS.aurora,
      distributorOrgId: ORGS.hongHa,
      relationshipType: "authorized_distributor",
      countries: ["VN"],
      validFrom: ctx.daysAgo(180),
      validTo: ctx.daysAhead(545),
      evidence: edgeEvidence(SOURCES.auroraCatalogue, "source_captured", 0.85),
    },
  ];

  const supplierListings: SupplierListing[] = [
    { ...ctx.canonical(LISTINGS.mekongTsa), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa500, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote, "source_captured", 0.85) },
    { ...ctx.canonical(LISTINGS.mekongTp), supplierOrgId: ORGS.mekong, skuId: SKUS.tsaPlates20, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote, "source_captured", 0.85) },
    { ...ctx.canonical(LISTINGS.mekongNb), supplierOrgId: ORGS.mekong, skuId: SKUS.nb500, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongAir), supplierOrgId: ORGS.mekong, skuId: SKUS.airAs100, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.condorCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongEm), supplierOrgId: ORGS.mekong, skuId: SKUS.emContact20, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongPc), supplierOrgId: ORGS.mekong, skuId: SKUS.pc50, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.condorCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonTd), supplierOrgId: ORGS.saigon, skuId: SKUS.tsaDelta500, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonSda), supplierOrgId: ORGS.saigon, skuId: SKUS.sdaPlates20, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonQc), supplierOrgId: ORGS.saigon, skuId: SKUS.qcBsub10, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonNa2), supplierOrgId: ORGS.saigon, skuId: SKUS.na2x500, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.deltaCatalogue, "source_captured", 0.75) },
    // Listed but with NO price and NO availability → incomplete_product_coverage signal.
    { ...ctx.canonical(LISTINGS.saigonSteri), supplierOrgId: ORGS.saigon, skuId: SKUS.steriCan10, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.condorCatalogue, "unverified", 0.5) },
    { ...ctx.canonical(LISTINGS.hongHaCc), supplierOrgId: ORGS.hongHa, skuId: SKUS.cc500, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote, "source_captured", 0.85) },
    { ...ctx.canonical(LISTINGS.hongHaCcp), supplierOrgId: ORGS.hongHa, skuId: SKUS.ccPlates20, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongSt200), supplierOrgId: ORGS.mekong, skuId: SKUS.st200, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonSp3000), supplierOrgId: ORGS.saigon, skuId: SKUS.sp3000, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonAg90), supplierOrgId: ORGS.saigon, skuId: SKUS.ag90, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonPc90), supplierOrgId: ORGS.saigon, skuId: SKUS.pc90, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonBiGst), supplierOrgId: ORGS.saigon, skuId: SKUS.biGst100, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonBiAmp), supplierOrgId: ORGS.saigon, skuId: SKUS.biAmp20, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.hongHaChoMax), supplierOrgId: ORGS.hongHa, skuId: SKUS.choMax10, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonFeed), supplierOrgId: ORGS.saigon, skuId: SKUS.feed1l, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongEtoh), supplierOrgId: ORGS.mekong, skuId: SKUS.etoh20l, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaPbs), supplierOrgId: ORGS.hongHa, skuId: SKUS.pbs5l, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonProa), supplierOrgId: ORGS.saigon, skuId: SKUS.proa1l, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongQmem), supplierOrgId: ORGS.mekong, skuId: SKUS.qmem10, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongSteriFlow), supplierOrgId: ORGS.mekong, skuId: SKUS.steriFlow3, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonTff), supplierOrgId: ORGS.saigon, skuId: SKUS.tff30k, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.hongHaEndoZyme), supplierOrgId: ORGS.hongHa, skuId: SKUS.endoZyme192, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonLal), supplierOrgId: ORGS.saigon, skuId: SKUS.lalCart50, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonSpCan), supplierOrgId: ORGS.saigon, skuId: SKUS.spCan10, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonDcp), supplierOrgId: ORGS.saigon, skuId: SKUS.dcp20, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaQcEcoli), supplierOrgId: ORGS.hongHa, skuId: SKUS.qcEcoli10, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongTurntable), supplierOrgId: ORGS.mekong, skuId: SKUS.turntable, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.7) },
    { ...ctx.canonical(LISTINGS.saigonLoops), supplierOrgId: ORGS.saigon, skuId: SKUS.loops1000, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongTsa100), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa100, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.mekongTsa5kg), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa5kg, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaChoMax100), supplierOrgId: ORGS.hongHa, skuId: SKUS.choMax100, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongSteriCan50), supplierOrgId: ORGS.mekong, skuId: SKUS.steriCan50, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaC18ps), supplierOrgId: ORGS.hongHa, skuId: SKUS.c18ps21, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.saigonC18as), supplierOrgId: ORGS.saigon, skuId: SKUS.c18as46, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongRs), supplierOrgId: ORGS.mekong, skuId: SKUS.rsAcet, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaCse), supplierOrgId: ORGS.hongHa, skuId: SKUS.cse10, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.hongHaWaterPa), supplierOrgId: ORGS.hongHa, skuId: SKUS.waterPa100, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonWaterMf), supplierOrgId: ORGS.saigon, skuId: SKUS.waterMf50, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.hongHaSub), supplierOrgId: ORGS.hongHa, skuId: SKUS.sub50, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.hongHaQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongSum), supplierOrgId: ORGS.mekong, skuId: SKUS.sum100, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.75) },
    { ...ctx.canonical(LISTINGS.mekongSt300), supplierOrgId: ORGS.mekong, skuId: SKUS.st300, relationshipType: "authorized_distributor", evidence: edgeEvidence(SOURCES.mekongQuote2, "source_captured", 0.8) },
    { ...ctx.canonical(LISTINGS.saigonSp1000), supplierOrgId: ORGS.saigon, skuId: SKUS.sp1000, relationshipType: "non_exclusive_distributor", evidence: edgeEvidence(SOURCES.saigonQuote2, "source_captured", 0.75) },
  ];

  const availabilityObservations: AvailabilityObservation[] = [
    { ...ctx.canonical(AVAILABILITY.tsaInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa500, country: "VN", observedAt: ctx.daysAgo(15), status: "in_stock", leadTimeDays: 7 },
    // Two stock issues for the same SKU + supplier inside 90 days → repeated_stock_issue.
    { ...ctx.canonical(AVAILABILITY.tpLimited), supplierOrgId: ORGS.mekong, skuId: SKUS.tsaPlates20, country: "VN", observedAt: ctx.daysAgo(30), status: "limited", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.tpOutOfStock), supplierOrgId: ORGS.mekong, skuId: SKUS.tsaPlates20, country: "VN", observedAt: ctx.daysAgo(10), status: "out_of_stock", leadTimeDays: 28 },
    { ...ctx.canonical(AVAILABILITY.sdaOutOfStock), supplierOrgId: ORGS.saigon, skuId: SKUS.sdaPlates20, country: "VN", observedAt: ctx.daysAgo(60), status: "out_of_stock", leadTimeDays: 35 },
    { ...ctx.canonical(AVAILABILITY.airInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.airAs100, country: "VN", observedAt: ctx.daysAgo(20), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.emInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.emContact20, country: "VN", observedAt: ctx.daysAgo(12), status: "in_stock", leadTimeDays: 10 },
    { ...ctx.canonical(AVAILABILITY.pcInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.pc50, country: "VN", observedAt: ctx.daysAgo(25), status: "in_stock", leadTimeDays: 30 },
    { ...ctx.canonical(AVAILABILITY.na2InStock), supplierOrgId: ORGS.saigon, skuId: SKUS.na2x500, country: "VN", observedAt: ctx.daysAgo(40), status: "in_stock", leadTimeDays: 12 },
    { ...ctx.canonical(AVAILABILITY.ccInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.cc500, country: "VN", observedAt: ctx.daysAgo(18), status: "in_stock", leadTimeDays: 10 },
    { ...ctx.canonical(AVAILABILITY.ccpInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.ccPlates20, country: "VN", observedAt: ctx.daysAgo(9), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.st200InStock), supplierOrgId: ORGS.mekong, skuId: SKUS.st200, country: "VN", observedAt: ctx.daysAgo(20), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.sp3000Limited), supplierOrgId: ORGS.saigon, skuId: SKUS.sp3000, country: "VN", observedAt: ctx.daysAgo(22), status: "limited", leadTimeDays: 45 },
    { ...ctx.canonical(AVAILABILITY.ag90InStock), supplierOrgId: ORGS.saigon, skuId: SKUS.ag90, country: "VN", observedAt: ctx.daysAgo(14), status: "in_stock", leadTimeDays: 30 },
    { ...ctx.canonical(AVAILABILITY.pc90InStock), supplierOrgId: ORGS.saigon, skuId: SKUS.pc90, country: "VN", observedAt: ctx.daysAgo(16), status: "in_stock", leadTimeDays: 30 },
    { ...ctx.canonical(AVAILABILITY.biGstInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.biGst100, country: "VN", observedAt: ctx.daysAgo(11), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.biAmpLimited), supplierOrgId: ORGS.saigon, skuId: SKUS.biAmp20, country: "VN", observedAt: ctx.daysAgo(13), status: "limited", leadTimeDays: 28 },
    { ...ctx.canonical(AVAILABILITY.choMaxInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.choMax10, country: "VN", observedAt: ctx.daysAgo(12), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.feedInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.feed1l, country: "VN", observedAt: ctx.daysAgo(10), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.etohInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.etoh20l, country: "VN", observedAt: ctx.daysAgo(8), status: "in_stock", leadTimeDays: 7 },
    { ...ctx.canonical(AVAILABILITY.pbsLimited), supplierOrgId: ORGS.hongHa, skuId: SKUS.pbs5l, country: "VN", observedAt: ctx.daysAgo(9), status: "limited", leadTimeDays: 28 },
    { ...ctx.canonical(AVAILABILITY.proaLimited), supplierOrgId: ORGS.saigon, skuId: SKUS.proa1l, country: "VN", observedAt: ctx.daysAgo(15), status: "limited", leadTimeDays: 45 },
    { ...ctx.canonical(AVAILABILITY.qmemInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.qmem10, country: "VN", observedAt: ctx.daysAgo(13), status: "in_stock", leadTimeDays: 30 },
    { ...ctx.canonical(AVAILABILITY.steriFlowInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.steriFlow3, country: "VN", observedAt: ctx.daysAgo(7), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.tffInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.tff30k, country: "VN", observedAt: ctx.daysAgo(14), status: "in_stock", leadTimeDays: 35 },
    { ...ctx.canonical(AVAILABILITY.endoZymeInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.endoZyme192, country: "VN", observedAt: ctx.daysAgo(6), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.lalInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.lalCart50, country: "VN", observedAt: ctx.daysAgo(9), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.spCanInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.spCan10, country: "VN", observedAt: ctx.daysAgo(10), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.dcpInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.dcp20, country: "VN", observedAt: ctx.daysAgo(8), status: "in_stock", leadTimeDays: 12 },
    { ...ctx.canonical(AVAILABILITY.qcEcoliInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.qcEcoli10, country: "VN", observedAt: ctx.daysAgo(7), status: "in_stock", leadTimeDays: 10 },
    { ...ctx.canonical(AVAILABILITY.turntableInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.turntable, country: "VN", observedAt: ctx.daysAgo(15), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.loopsInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.loops1000, country: "VN", observedAt: ctx.daysAgo(5), status: "in_stock", leadTimeDays: 7 },
    { ...ctx.canonical(AVAILABILITY.tsa100InStock), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa100, country: "VN", observedAt: ctx.daysAgo(12), status: "in_stock", leadTimeDays: 7 },
    { ...ctx.canonical(AVAILABILITY.tsa5kgInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.tsa5kg, country: "VN", observedAt: ctx.daysAgo(19), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.choMax100Limited), supplierOrgId: ORGS.hongHa, skuId: SKUS.choMax100, country: "VN", observedAt: ctx.daysAgo(11), status: "limited", leadTimeDays: 42 },
    { ...ctx.canonical(AVAILABILITY.steriCan50InStock), supplierOrgId: ORGS.mekong, skuId: SKUS.steriCan50, country: "VN", observedAt: ctx.daysAgo(9), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.c18psInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.c18ps21, country: "VN", observedAt: ctx.daysAgo(10), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.c18asInStock), supplierOrgId: ORGS.saigon, skuId: SKUS.c18as46, country: "VN", observedAt: ctx.daysAgo(12), status: "in_stock", leadTimeDays: 28 },
    { ...ctx.canonical(AVAILABILITY.rsInStock), supplierOrgId: ORGS.mekong, skuId: SKUS.rsAcet, country: "VN", observedAt: ctx.daysAgo(14), status: "in_stock", leadTimeDays: 21 },
    { ...ctx.canonical(AVAILABILITY.cseInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.cse10, country: "VN", observedAt: ctx.daysAgo(8), status: "in_stock", leadTimeDays: 14 },
    { ...ctx.canonical(AVAILABILITY.waterPaInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.waterPa100, country: "VN", observedAt: ctx.daysAgo(6), status: "in_stock", leadTimeDays: 10 },
    { ...ctx.canonical(AVAILABILITY.waterMfLimited), supplierOrgId: ORGS.saigon, skuId: SKUS.waterMf50, country: "VN", observedAt: ctx.daysAgo(11), status: "limited", leadTimeDays: 35 },
    { ...ctx.canonical(AVAILABILITY.subInStock), supplierOrgId: ORGS.hongHa, skuId: SKUS.sub50, country: "VN", observedAt: ctx.daysAgo(13), status: "in_stock", leadTimeDays: 30 },
    { ...ctx.canonical(AVAILABILITY.sumLimited), supplierOrgId: ORGS.mekong, skuId: SKUS.sum100, country: "VN", observedAt: ctx.daysAgo(12), status: "limited", leadTimeDays: 40 },
    { ...ctx.canonical(AVAILABILITY.st300InStock), supplierOrgId: ORGS.mekong, skuId: SKUS.st300, country: "VN", observedAt: ctx.daysAgo(18), status: "in_stock", leadTimeDays: 28 },
    { ...ctx.canonical(AVAILABILITY.sp1000Limited), supplierOrgId: ORGS.saigon, skuId: SKUS.sp1000, country: "VN", observedAt: ctx.daysAgo(20), status: "limited", leadTimeDays: 50 },
  ];

  const commercialTerms: CommercialTerms[] = [
    {
      ...ctx.tenantPrivate(COMMERCIAL_TERMS.mekong, DEMO_TENANT_ID),
      supplierOrgId: ORGS.mekong,
      moq: 5,
      moqUnit: "pack",
      paymentTerms: "Net 30",
      incoterm: "DAP",
      currency: "VND",
      validFrom: ctx.daysAgo(200),
      validTo: ctx.daysAhead(165),
      notes: "Framework terms negotiated 2026 cycle (Demo).",
    },
    {
      ...ctx.tenantPrivate(COMMERCIAL_TERMS.saigon, DEMO_TENANT_ID),
      supplierOrgId: ORGS.saigon,
      moq: 1,
      moqUnit: "pack",
      paymentTerms: "Net 45",
      incoterm: "CIF",
      currency: "VND",
      validFrom: ctx.daysAgo(150),
      validTo: ctx.daysAhead(215),
      notes: "Non-exclusive terms; import lead times apply (Demo).",
    },
    {
      ...ctx.tenantPrivate(COMMERCIAL_TERMS.hongHa, DEMO_TENANT_ID),
      supplierOrgId: ORGS.hongHa,
      moq: 2,
      moqUnit: "pack",
      paymentTerms: "Net 30",
      incoterm: "DAP",
      currency: "VND",
      validFrom: ctx.daysAgo(100),
      validTo: ctx.daysAhead(265),
      notes: "Northern deliveries from Ha Noi warehouse (Demo).",
    },
  ];

  const rawPrices: PriceObservation[] = [
    {
      // 400 days old, superseded in practice by price-tsa-new (+23.9 % → unusual_price_increase).
      ...ctx.canonical(PRICES.tsaOld),
      skuId: SKUS.tsa500,
      packConfigurationId: PACKS.tsa500,
      supplierOrgId: ORGS.mekong,
      originalAmount: 2_300_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(400),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.mekongQuoteOld,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.tsaNew),
      skuId: SKUS.tsa500,
      packConfigurationId: PACKS.tsa500,
      supplierOrgId: ORGS.mekong,
      originalAmount: 2_850_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(20),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.8),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.tp),
      skuId: SKUS.tsaPlates20,
      packConfigurationId: PACKS.tsaPlates20,
      supplierOrgId: ORGS.mekong,
      originalAmount: 1_150_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(18),
      taxIncluded: true,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.8),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.nb),
      skuId: SKUS.nb500,
      packConfigurationId: PACKS.nb500,
      supplierOrgId: ORGS.mekong,
      originalAmount: 1_650_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(90),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "EXW",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.6),
      evidenceState: "unverified",
      isSynthetic: true,
    },
    {
      // Tenant-private quoted price (USD, EXW).
      ...ctx.canonical(PRICES.tdNew),
      visibility: "tenant_private",
      skuId: SKUS.tsaDelta500,
      packConfigurationId: PACKS.tsaDelta500,
      supplierOrgId: ORGS.saigon,
      originalAmount: 98,
      originalCurrency: "USD",
      observationDate: ctx.daysAgo(30),
      taxIncluded: false,
      incoterm: "EXW",
      geography: "VN",
      customerSegment: "pharma_qc",
      quantity: 1,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.75),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.tdOld),
      visibility: "tenant_private",
      skuId: SKUS.tsaDelta500,
      packConfigurationId: PACKS.tsaDelta500,
      supplierOrgId: ORGS.saigon,
      originalAmount: 96,
      originalCurrency: "USD",
      observationDate: ctx.daysAgo(200),
      taxIncluded: false,
      incoterm: "EXW",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.6),
      evidenceState: "unverified",
      isSynthetic: true,
    },
    {
      // Stale (>180 days): latest observation for this SKU → price_stale signal.
      ...ctx.canonical(PRICES.sdaStale),
      skuId: SKUS.sdaPlates20,
      packConfigurationId: PACKS.sda20,
      supplierOrgId: ORGS.saigon,
      originalAmount: 980_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(200),
      taxIncluded: true,
      vatRate: 0.08,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.importRecord,
      confidence: confidence(0.5),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.qc),
      visibility: "tenant_private",
      skuId: SKUS.qcBsub10,
      packConfigurationId: PACKS.qcBsub10,
      supplierOrgId: ORGS.saigon,
      originalAmount: 145,
      originalCurrency: "USD",
      observationDate: ctx.daysAgo(45),
      taxIncluded: false,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.75),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.em),
      skuId: SKUS.emContact20,
      packConfigurationId: PACKS.emContact20,
      supplierOrgId: ORGS.mekong,
      originalAmount: 720_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(15),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.internalNote,
      confidence: confidence(0.55),
      evidenceState: "unverified",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.ccOld),
      skuId: SKUS.cc500,
      packConfigurationId: PACKS.cc500,
      supplierOrgId: ORGS.hongHa,
      originalAmount: 3_200_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(150),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.auroraCatalogue,
      confidence: confidence(0.6),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      // Modest +7.8% over ccOld — normal drift, below the unusual-increase threshold.
      ...ctx.canonical(PRICES.ccNew),
      skuId: SKUS.cc500,
      packConfigurationId: PACKS.cc500,
      supplierOrgId: ORGS.hongHa,
      originalAmount: 3_450_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(25),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.hongHaQuote,
      confidence: confidence(0.75),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.ccp),
      skuId: SKUS.ccPlates20,
      packConfigurationId: PACKS.ccPlates20,
      supplierOrgId: ORGS.hongHa,
      originalAmount: 1_280_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(25),
      taxIncluded: true,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.hongHaQuote,
      confidence: confidence(0.75),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.st200),
      skuId: SKUS.st200,
      packConfigurationId: PACKS.st200,
      supplierOrgId: ORGS.mekong,
      originalAmount: 185_000_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(20),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.mekongQuote,
      confidence: confidence(0.75),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.sp3000),
      skuId: SKUS.sp3000,
      packConfigurationId: PACKS.sp3000,
      supplierOrgId: ORGS.saigon,
      originalAmount: 162_000_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(22),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.ag90),
      skuId: SKUS.ag90,
      packConfigurationId: PACKS.ag90,
      supplierOrgId: ORGS.saigon,
      originalAmount: 78_000_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(22),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.pc90),
      skuId: SKUS.pc90,
      packConfigurationId: PACKS.pc90,
      supplierOrgId: ORGS.saigon,
      originalAmount: 96_000_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(22),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.biGst),
      skuId: SKUS.biGst100,
      packConfigurationId: PACKS.biGst100,
      supplierOrgId: ORGS.saigon,
      originalAmount: 4_600_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(30),
      taxIncluded: false,
      vatRate: 0.1,
      incoterm: "CIF",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.biAmp),
      skuId: SKUS.biAmp20,
      packConfigurationId: PACKS.biAmp20,
      supplierOrgId: ORGS.saigon,
      originalAmount: 3_150_000,
      originalCurrency: "VND",
      observationDate: ctx.daysAgo(22),
      taxIncluded: true,
      vatRate: 0.1,
      incoterm: "DAP",
      geography: "VN",
      quantity: 1,
      sourceId: SOURCES.saigonQuote2,
      confidence: confidence(0.7),
      evidenceState: "source_captured",
      isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.choMax),
      skuId: SKUS.choMax10, packConfigurationId: PACKS.choMax10, supplierOrgId: ORGS.hongHa,
      originalAmount: 8_900_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.feed),
      skuId: SKUS.feed1l, packConfigurationId: PACKS.feed1l, supplierOrgId: ORGS.saigon,
      originalAmount: 5_400_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.etoh),
      skuId: SKUS.etoh20l, packConfigurationId: PACKS.etoh20l, supplierOrgId: ORGS.mekong,
      originalAmount: 4_200_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.pbs),
      skuId: SKUS.pbs5l, packConfigurationId: PACKS.pbs5l, supplierOrgId: ORGS.hongHa,
      originalAmount: 2_350_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.proa),
      skuId: SKUS.proa1l, packConfigurationId: PACKS.proa1l, supplierOrgId: ORGS.saigon,
      originalAmount: 385_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.qmem),
      skuId: SKUS.qmem10, packConfigurationId: PACKS.qmem10, supplierOrgId: ORGS.mekong,
      originalAmount: 68_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.steriFlow),
      skuId: SKUS.steriFlow3, packConfigurationId: PACKS.steriFlow3, supplierOrgId: ORGS.mekong,
      originalAmount: 21_500_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.tff),
      skuId: SKUS.tff30k, packConfigurationId: PACKS.tff30k, supplierOrgId: ORGS.saigon,
      originalAmount: 42_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.endoZyme),
      skuId: SKUS.endoZyme192, packConfigurationId: PACKS.endoZyme192, supplierOrgId: ORGS.hongHa,
      originalAmount: 28_500_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: true, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.lal),
      skuId: SKUS.lalCart50, packConfigurationId: PACKS.lalCart50, supplierOrgId: ORGS.saigon,
      originalAmount: 9_800_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.spCan),
      skuId: SKUS.spCan10, packConfigurationId: PACKS.spCan10, supplierOrgId: ORGS.saigon,
      originalAmount: 4_900_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.dcp),
      skuId: SKUS.dcp20, packConfigurationId: PACKS.dcp20, supplierOrgId: ORGS.saigon,
      originalAmount: 890_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: true, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.qcEcoli),
      skuId: SKUS.qcEcoli10, packConfigurationId: PACKS.qcEcoli10, supplierOrgId: ORGS.hongHa,
      originalAmount: 2_650_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.turntable),
      skuId: SKUS.turntable, packConfigurationId: PACKS.turntable, supplierOrgId: ORGS.mekong,
      originalAmount: 6_400_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.loops),
      skuId: SKUS.loops1000, packConfigurationId: PACKS.loops1000, supplierOrgId: ORGS.saigon,
      originalAmount: 1_450_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    // -- Pack-variant prices (bulk beats unit price per gram/litre) --------------
    {
      ...ctx.canonical(PRICES.tsa100),
      skuId: SKUS.tsa100, packConfigurationId: PACKS.tsa100, supplierOrgId: ORGS.mekong,
      originalAmount: 790_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.tsa5kg),
      skuId: SKUS.tsa5kg, packConfigurationId: PACKS.tsa5kg, supplierOrgId: ORGS.mekong,
      originalAmount: 24_500_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.choMax100),
      skuId: SKUS.choMax100, packConfigurationId: PACKS.choMax100, supplierOrgId: ORGS.hongHa,
      originalAmount: 79_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.steriCan50),
      skuId: SKUS.steriCan50, packConfigurationId: PACKS.steriCan50, supplierOrgId: ORGS.mekong,
      originalAmount: 21_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    // -- History pairs: modest drift, both below the unusual-increase threshold ---
    {
      ...ctx.canonical(PRICES.spCanOld),
      skuId: SKUS.spCan10, packConfigurationId: PACKS.spCan10, supplierOrgId: ORGS.saigon,
      originalAmount: 4_500_000, originalCurrency: "VND", observationDate: ctx.daysAgo(170),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.importRecord, confidence: confidence(0.6), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.proaOld),
      skuId: SKUS.proa1l, packConfigurationId: PACKS.proa1l, supplierOrgId: ORGS.saigon,
      originalAmount: 340_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(190),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.importRecord, confidence: confidence(0.6), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.c18ps),
      skuId: SKUS.c18ps21, packConfigurationId: PACKS.c18ps21, supplierOrgId: ORGS.hongHa,
      originalAmount: 18_500_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.c18as),
      skuId: SKUS.c18as46, packConfigurationId: PACKS.c18as46, supplierOrgId: ORGS.saigon,
      originalAmount: 12_900_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.rsAcet),
      skuId: SKUS.rsAcet, packConfigurationId: PACKS.rsAcet, supplierOrgId: ORGS.mekong,
      originalAmount: 5_900_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.cse),
      skuId: SKUS.cse10, packConfigurationId: PACKS.cse10, supplierOrgId: ORGS.hongHa,
      originalAmount: 11_200_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.waterPa),
      skuId: SKUS.waterPa100, packConfigurationId: PACKS.waterPa100, supplierOrgId: ORGS.hongHa,
      originalAmount: 6_800_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: true, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.waterMf),
      skuId: SKUS.waterMf50, packConfigurationId: PACKS.waterMf50, supplierOrgId: ORGS.saigon,
      originalAmount: 4_150_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.sub50),
      skuId: SKUS.sub50, packConfigurationId: PACKS.sub50, supplierOrgId: ORGS.hongHa,
      originalAmount: 14_800_000, originalCurrency: "VND", observationDate: ctx.daysAgo(18),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.hongHaQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.sum100),
      skuId: SKUS.sum100, packConfigurationId: PACKS.sum100, supplierOrgId: ORGS.mekong,
      originalAmount: 11_600_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.st300),
      skuId: SKUS.st300, packConfigurationId: PACKS.st300, supplierOrgId: ORGS.mekong,
      originalAmount: 298_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(16),
      taxIncluded: false, vatRate: 0.1, incoterm: "DAP", geography: "VN", quantity: 1,
      sourceId: SOURCES.mekongQuote2, confidence: confidence(0.75), evidenceState: "source_captured", isSynthetic: true,
    },
    {
      ...ctx.canonical(PRICES.sp1000),
      skuId: SKUS.sp1000, packConfigurationId: PACKS.sp1000, supplierOrgId: ORGS.saigon,
      originalAmount: 96_000_000, originalCurrency: "VND", observationDate: ctx.daysAgo(22),
      taxIncluded: false, vatRate: 0.1, incoterm: "CIF", geography: "VN", quantity: 1,
      sourceId: SOURCES.saigonQuote2, confidence: confidence(0.7), evidenceState: "source_captured", isSynthetic: true,
    },
  ];

  // Fill normalized per-unit / per-test fields with the domain engine so the
  // seeded values are exactly what normalization would compute (never guessed).
  const priceObservations = rawPrices.map((observation) => {
    const pack = observation.packConfigurationId
      ? packConfigurations.find((candidate) => candidate.id === observation.packConfigurationId) ?? null
      : null;
    return normalizePrice(observation, pack, { yieldPerUnit: YIELD_PER_UNIT[observation.skuId] }).observation;
  });

  const priceComponents: PriceComponent[] = [
    {
      ...ctx.canonical(PRICE_COMPONENTS.qcFreight),
      priceObservationId: PRICES.qc,
      kind: "freight",
      amount: 12,
      currency: "USD",
    },
    {
      ...ctx.canonical(PRICE_COMPONENTS.sdaDuty),
      priceObservationId: PRICES.sdaStale,
      kind: "import_duty",
      amount: 45_000,
      currency: "VND",
    },
  ];

  return {
    supplier_profile: supplierProfiles,
    distribution_agreement: distributionAgreements,
    supplier_listing: supplierListings,
    availability_observation: availabilityObservations,
    commercial_terms: commercialTerms,
    price_observation: priceObservations,
    price_component: priceComponents,
  };
}
