import type {
  Application,
  Brand,
  IncubationCondition,
  Industry,
  Method,
  Organism,
  PackConfiguration,
  PreparationMethod,
  Product,
  ProductDocument,
  ProductEdge,
  ProductFamily,
  ProductFormat,
  SampleType,
  Sku,
  Standard,
  StandardVersion,
  TestType,
} from "@/lib/domain/types";

import { edgeEvidence, type SeedContext } from "./context";
import {
  APPLICATIONS,
  BRANDS,
  FAMILIES,
  FORMATS,
  INCUBATION,
  INDUSTRIES,
  METHODS,
  ORGANISMS,
  ORGS,
  PACKS,
  PREPARATION,
  PRODUCTS,
  SAMPLE_TYPES,
  SKUS,
  SOURCES,
  STANDARDS,
  STANDARD_VERSIONS,
  TEST_TYPES,
} from "./ids";
import type { DemoDatasetSlices } from "./types";

/**
 * Product graph fixtures: 10 manufacturers, 14 brands, 32 families across 15
 * categories, 35 products and 36 SKUs — spanning the upstream → downstream →
 * QC portfolio for Pharma API and Biopharma, the microbiology wedge with a
 * discontinued SKU with a successor and an import-created near-duplicate SKU —
 * plus the scientific / regulatory reference entities and the
 * evidence-carrying product edges that make "research a product" demonstrable.
 */
export function seedProducts(ctx: SeedContext): DemoDatasetSlices {
  const brands: Brand[] = [
    { ...ctx.canonical(BRANDS.acmeMedia), ownerOrganizationId: ORGS.acme, name: "Acme Media (Demo)" },
    { ...ctx.canonical(BRANDS.deltaBio), ownerOrganizationId: ORGS.deltaBio, name: "DeltaBio (Demo)" },
    { ...ctx.canonical(BRANDS.condorAir), ownerOrganizationId: ORGS.condor, name: "Condor Air (Demo)" },
    { ...ctx.canonical(BRANDS.condorSteri), ownerOrganizationId: ORGS.condor, name: "Condor Steri (Demo)" },
    { ...ctx.canonical(BRANDS.auroraChrom), ownerOrganizationId: ORGS.aurora, name: "AuroraChrom (Demo)" },
    { ...ctx.canonical(BRANDS.steripump), ownerOrganizationId: ORGS.meridian, name: "SteriPump (Demo)" },
    { ...ctx.canonical(BRANDS.meridianAir), ownerOrganizationId: ORGS.meridian, name: "Meridian Air (Demo)" },
    { ...ctx.canonical(BRANDS.steriSure), ownerOrganizationId: ORGS.meridian, name: "SteriSure (Demo)" },
    { ...ctx.canonical(BRANDS.novaraCell), ownerOrganizationId: ORGS.novara, name: "NovaraCell (Demo)" },
    { ...ctx.canonical(BRANDS.kestrelFlow), ownerOrganizationId: ORGS.kestrel, name: "KestrelFlow (Demo)" },
    { ...ctx.canonical(BRANDS.auriSelect), ownerOrganizationId: ORGS.auriga, name: "AuriSelect (Demo)" },
    { ...ctx.canonical(BRANDS.vestaPure), ownerOrganizationId: ORGS.vesta, name: "VestaPure (Demo)" },
    { ...ctx.canonical(BRANDS.orizonEndo), ownerOrganizationId: ORGS.orizon, name: "OrizonEndo (Demo)" },
    { ...ctx.canonical(BRANDS.orizonQc), ownerOrganizationId: ORGS.orizon, name: "OrizonQC (Demo)" },
  ];

  const productFamilies: ProductFamily[] = [
    { ...ctx.canonical(FAMILIES.acmeDehydra), brandId: BRANDS.acmeMedia, name: "AcmeDehydra dehydrated media (Demo)", category: "dehydrated_culture_media" },
    { ...ctx.canonical(FAMILIES.acmePlates), brandId: BRANDS.acmeMedia, name: "AcmePlate ready media (Demo)", category: "ready_prepared_media" },
    { ...ctx.canonical(FAMILIES.deltaMedia), brandId: BRANDS.deltaBio, name: "DeltaBio dehydrated media (Demo)", category: "dehydrated_culture_media" },
    { ...ctx.canonical(FAMILIES.deltaPlates), brandId: BRANDS.deltaBio, name: "DeltaPlate ready media (Demo)", category: "ready_prepared_media" },
    { ...ctx.canonical(FAMILIES.deltaQc), brandId: BRANDS.deltaBio, name: "DeltaSeed QC organisms (Demo)", category: "microbial_reference_materials" },
    { ...ctx.canonical(FAMILIES.condorAir), brandId: BRANDS.condorAir, name: "Condor air sampling (Demo)", category: "air_samplers" },
    { ...ctx.canonical(FAMILIES.condorEm), brandId: BRANDS.condorAir, name: "Condor EM consumables (Demo)", category: "environmental_monitoring_consumables" },
    { ...ctx.canonical(FAMILIES.condorCount), brandId: BRANDS.condorAir, name: "Condor particle counting (Demo)", category: "particle_counters" },
    { ...ctx.canonical(FAMILIES.condorSteri), brandId: BRANDS.condorSteri, name: "CondorSter sterility consumables (Demo)", category: "sterility_testing_consumables" },
    { ...ctx.canonical(FAMILIES.auroraChrom), brandId: BRANDS.auroraChrom, name: "AuroraChrom chromogenic dehydrated media (Demo)", category: "dehydrated_culture_media" },
    { ...ctx.canonical(FAMILIES.auroraPlates), brandId: BRANDS.auroraChrom, name: "AuroraChrom ready plates (Demo)", category: "ready_prepared_media" },
    { ...ctx.canonical(FAMILIES.condorSteriPump), brandId: BRANDS.condorSteri, name: "CondorSter sterility testing systems (Demo)", category: "sterility_testing_equipment" },
    { ...ctx.canonical(FAMILIES.steripump), brandId: BRANDS.steripump, name: "SteriPump closed sterility testing systems (Demo)", category: "sterility_testing_equipment" },
    { ...ctx.canonical(FAMILIES.meridianAir), brandId: BRANDS.meridianAir, name: "Meridian air sampling (Demo)", category: "air_samplers" },
    { ...ctx.canonical(FAMILIES.meridianCount), brandId: BRANDS.meridianAir, name: "Meridian particle counting (Demo)", category: "particle_counters" },
    { ...ctx.canonical(FAMILIES.deltaBi), brandId: BRANDS.deltaBio, name: "DeltaSeed biological indicators (Demo)", category: "biological_indicators" },
    { ...ctx.canonical(FAMILIES.steriSureBi), brandId: BRANDS.steriSure, name: "SteriSure biological indicators (Demo)", category: "biological_indicators" },
    // -- Upstream (biopharma cell culture + API process chemicals) --------------
    { ...ctx.canonical(FAMILIES.choMax), brandId: BRANDS.novaraCell, name: "NovaraCell CHO media (Demo)", category: "cell_culture_media" },
    { ...ctx.canonical(FAMILIES.deltaGrow), brandId: BRANDS.deltaBio, name: "DeltaGrow cell culture feeds (Demo)", category: "cell_culture_media" },
    { ...ctx.canonical(FAMILIES.vestaSolvents), brandId: BRANDS.vestaPure, name: "VestaPure high-purity solvents (Demo)", category: "process_chemicals" },
    { ...ctx.canonical(FAMILIES.novaraBuffers), brandId: BRANDS.novaraCell, name: "NovaraCell process buffers (Demo)", category: "process_chemicals" },
    // -- Downstream (chromatography + filtration) -------------------------------
    { ...ctx.canonical(FAMILIES.auriSelectResin), brandId: BRANDS.auriSelect, name: "AuriSelect affinity resins (Demo)", category: "purification_chromatography" },
    { ...ctx.canonical(FAMILIES.kestrelMembrane), brandId: BRANDS.kestrelFlow, name: "KestrelFlow membrane chromatography (Demo)", category: "purification_chromatography" },
    { ...ctx.canonical(FAMILIES.kestrelSteriFlow), brandId: BRANDS.kestrelFlow, name: "KestrelFlow sterilizing-grade filtration (Demo)", category: "process_filtration" },
    { ...ctx.canonical(FAMILIES.auriFlow), brandId: BRANDS.auriSelect, name: "AuriFlow TFF cassettes (Demo)", category: "process_filtration" },
    // -- QC (endotoxin) -----------------------------------------------------------
    { ...ctx.canonical(FAMILIES.endoZyme), brandId: BRANDS.orizonEndo, name: "OrizonEndo recombinant endotoxin assays (Demo)", category: "endotoxin_testing" },
    { ...ctx.canonical(FAMILIES.deltaTest), brandId: BRANDS.deltaBio, name: "DeltaTest LAL assays (Demo)", category: "endotoxin_testing" },
    // -- Shelf completion: second brand per consumable/QC/accessory shelf ---------
    { ...ctx.canonical(FAMILIES.spCan), brandId: BRANDS.steripump, name: "SteriPump sterility canisters (Demo)", category: "sterility_testing_consumables" },
    { ...ctx.canonical(FAMILIES.deltaEm), brandId: BRANDS.deltaBio, name: "DeltaEM monitoring plates (Demo)", category: "environmental_monitoring_consumables" },
    { ...ctx.canonical(FAMILIES.orizonQc), brandId: BRANDS.orizonQc, name: "OrizonQC reference materials (Demo)", category: "microbial_reference_materials" },
    { ...ctx.canonical(FAMILIES.condorAccessories), brandId: BRANDS.condorSteri, name: "CondorSter lab accessories (Demo)", category: "microbiology_lab_accessories" },
    { ...ctx.canonical(FAMILIES.meridianAccessories), brandId: BRANDS.steripump, name: "SteriPump lab accessories (Demo)", category: "microbiology_lab_accessories" },
  ];

  const products: Product[] = [
    {
      ...ctx.canonical(PRODUCTS.tsaAcme),
      familyId: FAMILIES.acmeDehydra,
      manufacturerOrganizationId: ORGS.acme,
      name: "Tryptic Soy Agar (TSA) (Demo)",
      category: "dehydrated_culture_media",
      description: "General-purpose growth medium for aerobic microorganisms (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.tsaPlatesAcme),
      familyId: FAMILIES.acmePlates,
      manufacturerOrganizationId: ORGS.acme,
      name: "TSA ready plates 90 mm (Demo)",
      category: "ready_prepared_media",
      description: "Ready-to-use 90 mm TSA plates for environmental monitoring (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.nbAcme),
      familyId: FAMILIES.acmeDehydra,
      manufacturerOrganizationId: ORGS.acme,
      name: "Nutrient Broth (NB) (Demo)",
      category: "dehydrated_culture_media",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.tsaDelta),
      familyId: FAMILIES.deltaMedia,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "Tryptic Soy Agar dehydrated (Demo)",
      category: "dehydrated_culture_media",
      description: "DeltaBio equivalent of TSA dehydrated medium (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.sdaPlatesDelta),
      familyId: FAMILIES.deltaPlates,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "Sabouraud Dextrose Agar ready plates (Demo)",
      category: "ready_prepared_media",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.qcDelta),
      familyId: FAMILIES.deltaQc,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "Bacillus subtilis ATCC 6633 QC pellets (Demo)",
      category: "microbial_reference_materials",
      status: "active",
    },
    {
      // Discontinued competitor product with a named successor.
      ...ctx.canonical(PRODUCTS.naDeltaOld),
      familyId: FAMILIES.deltaMedia,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "Nutrient Agar legacy formula (Demo)",
      category: "dehydrated_culture_media",
      status: "discontinued",
      successorProductId: PRODUCTS.naDelta,
    },
    {
      ...ctx.canonical(PRODUCTS.naDelta),
      familyId: FAMILIES.deltaMedia,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "Nutrient Agar NA-2 (Demo)",
      category: "dehydrated_culture_media",
      status: "active",
      predecessorProductId: PRODUCTS.naDeltaOld,
    },
    {
      ...ctx.canonical(PRODUCTS.airCondor),
      familyId: FAMILIES.condorAir,
      manufacturerOrganizationId: ORGS.condor,
      name: "Condor AirSampler AS-100 (Demo)",
      category: "air_samplers",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.emCondor),
      familyId: FAMILIES.condorEm,
      manufacturerOrganizationId: ORGS.condor,
      name: "AS-100 contact plates (Demo)",
      category: "environmental_monitoring_consumables",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.pcCondor),
      familyId: FAMILIES.condorCount,
      manufacturerOrganizationId: ORGS.condor,
      name: "CondorCount PC-50 particle counter (Demo)",
      category: "particle_counters",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.steriCondor),
      familyId: FAMILIES.condorSteri,
      manufacturerOrganizationId: ORGS.condor,
      name: "SteriCan sterility test canisters (Demo)",
      category: "sterility_testing_consumables",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.ccAurora),
      familyId: FAMILIES.auroraChrom,
      manufacturerOrganizationId: ORGS.aurora,
      name: "AuroraChrom Coliform Agar (Demo)",
      category: "dehydrated_culture_media",
      description: "Chromogenic selective medium for coliform / E. coli detection in food and dairy (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.ccPlatesAurora),
      familyId: FAMILIES.auroraPlates,
      manufacturerOrganizationId: ORGS.aurora,
      name: "AuroraChrom Listeria ready plates 90 mm (Demo)",
      category: "ready_prepared_media",
      description: "Ready-to-use chromogenic plates for Listeria monocytogenes detection (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.st200Condor),
      familyId: FAMILIES.condorSteriPump,
      manufacturerOrganizationId: ORGS.condor,
      name: "SteriTest ST-200 closed sterility testing system (Demo)",
      category: "sterility_testing_equipment",
      description: "Closed membrane-filtration sterility testing pump for SteriCan canisters, peristaltic 3-roller head (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.sp3000Meridian),
      familyId: FAMILIES.steripump,
      manufacturerOrganizationId: ORGS.meridian,
      name: "SteriPump SP-3000 closed sterility testing system (Demo)",
      category: "sterility_testing_equipment",
      description: "Closed sterility testing system with integrated canister docking and electronic flow control (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.ag90Meridian),
      familyId: FAMILIES.meridianAir,
      manufacturerOrganizationId: ORGS.meridian,
      name: "AirGuard AG-90 microbial air sampler (Demo)",
      category: "air_samplers",
      description: "Portable 90 L/min active air sampler using standard 90 mm plates (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.pc90Meridian),
      familyId: FAMILIES.meridianCount,
      manufacturerOrganizationId: ORGS.meridian,
      name: "PartiCount PC-90 handheld particle counter (Demo)",
      category: "particle_counters",
      description: "Handheld 0.3 um particle counter for cleanroom spot checks (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.biDelta),
      familyId: FAMILIES.deltaBi,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "DeltaSeed G. stearothermophilus spore strips (Demo)",
      category: "biological_indicators",
      description: "Spore strip biological indicators for steam sterilization validation (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.biSteriSure),
      familyId: FAMILIES.steriSureBi,
      manufacturerOrganizationId: ORGS.meridian,
      name: "SteriSure self-contained BI ampoules (Demo)",
      category: "biological_indicators",
      description: "Self-contained biological indicator ampoules for steam cycles, 48 h readout (Demo).",
      status: "active",
    },
    // -- Upstream: cell culture media (biopharma) --------------------------------
    {
      ...ctx.canonical(PRODUCTS.choMaxNovara),
      familyId: FAMILIES.choMax,
      manufacturerOrganizationId: ORGS.novara,
      name: "CHO-Max basal medium (Demo)",
      category: "cell_culture_media",
      description: "Chemically defined basal medium for CHO fed-batch mAb production (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.feedDelta),
      familyId: FAMILIES.deltaGrow,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "DeltaGrow CHO feed supplement (Demo)",
      category: "cell_culture_media",
      description: "Concentrated fed-batch feed for CHO cultures (Demo).",
      status: "active",
    },
    // -- Upstream: process chemicals (API + buffers) ------------------------------
    {
      ...ctx.canonical(PRODUCTS.etohVesta),
      familyId: FAMILIES.vestaSolvents,
      manufacturerOrganizationId: ORGS.vesta,
      name: "VestaPure ethanol 96% USP grade (Demo)",
      category: "process_chemicals",
      description: "High-purity ethanol for API synthesis and equipment sanitization (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.pbsNovara),
      familyId: FAMILIES.novaraBuffers,
      manufacturerOrganizationId: ORGS.novara,
      name: "NovaraCell PBS concentrate 10x (Demo)",
      category: "process_chemicals",
      description: "Phosphate-buffered saline concentrate for upstream and downstream steps (Demo).",
      status: "active",
    },
    // -- Downstream: chromatography ------------------------------------------------
    {
      ...ctx.canonical(PRODUCTS.proaAuriga),
      familyId: FAMILIES.auriSelectResin,
      manufacturerOrganizationId: ORGS.auriga,
      name: "AuriSelect Protein A resin (Demo)",
      category: "purification_chromatography",
      description: "Affinity resin for mAb capture from clarified harvest (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.qKestrel),
      familyId: FAMILIES.kestrelMembrane,
      manufacturerOrganizationId: ORGS.kestrel,
      name: "KestrelFlow Q membrane chromatography capsules (Demo)",
      category: "purification_chromatography",
      description: "Anion-exchange membrane capsules for flow-through polishing (Demo).",
      status: "active",
    },
    // -- Downstream: filtration ------------------------------------------------------
    {
      ...ctx.canonical(PRODUCTS.steriFlowKestrel),
      familyId: FAMILIES.kestrelSteriFlow,
      manufacturerOrganizationId: ORGS.kestrel,
      name: "SteriFlow 0.22 um sterilizing-grade cartridges (Demo)",
      category: "process_filtration",
      description: "Sterilizing-grade PES membrane cartridges for final fill filtration (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.tffAuriga),
      familyId: FAMILIES.auriFlow,
      manufacturerOrganizationId: ORGS.auriga,
      name: "AuriFlow TFF cassette 30 kDa (Demo)",
      category: "process_filtration",
      description: "Tangential-flow filtration cassette for concentration and diafiltration (Demo).",
      status: "active",
    },
    // -- QC: endotoxin testing -------------------------------------------------------
    {
      ...ctx.canonical(PRODUCTS.endoZymeOrizon),
      familyId: FAMILIES.endoZyme,
      manufacturerOrganizationId: ORGS.orizon,
      name: "EndoZyme rFC kinetic assay kit (Demo)",
      category: "endotoxin_testing",
      description: "Recombinant Factor C kinetic fluorescent endotoxin assay, animal-free (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.lalDelta),
      familyId: FAMILIES.deltaTest,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "DeltaTest LAL gel-clot cartridges (Demo)",
      category: "endotoxin_testing",
      description: "Limulus amebocyte lysate gel-clot cartridges for routine release testing (Demo).",
      status: "active",
    },
    // -- Shelf completion products -------------------------------------------------
    {
      ...ctx.canonical(PRODUCTS.spCanMeridian),
      familyId: FAMILIES.spCan,
      manufacturerOrganizationId: ORGS.meridian,
      name: "SteriPump closed sterility canisters (Demo)",
      category: "sterility_testing_consumables",
      description: "Closed sterility test canisters with dual 0.45 um membranes for the SP-3000 dock (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.dcpDelta),
      familyId: FAMILIES.deltaEm,
      manufacturerOrganizationId: ORGS.deltaBio,
      name: "DeltaPlate contact plates 55 mm (Demo)",
      category: "environmental_monitoring_consumables",
      description: "TSA contact plates with neutralizers for surface monitoring (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.qcEcoliOrizon),
      familyId: FAMILIES.orizonQc,
      manufacturerOrganizationId: ORGS.orizon,
      name: "OrizonQC E. coli ATCC 8739 QC pellets (Demo)",
      category: "microbial_reference_materials",
      description: "Lyophilized QC pellets, enumerated ≤100 CFU per pellet (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.turntableCondor),
      familyId: FAMILIES.condorAccessories,
      manufacturerOrganizationId: ORGS.condor,
      name: "Condor PetriTurn plate turntable (Demo)",
      category: "microbiology_lab_accessories",
      description: "Manual rotating turntable for even spread-plate inoculation (Demo).",
      status: "active",
    },
    {
      ...ctx.canonical(PRODUCTS.loopsMeridian),
      familyId: FAMILIES.meridianAccessories,
      manufacturerOrganizationId: ORGS.meridian,
      name: "SteriPump inoculating loops 10 uL sterile (Demo)",
      category: "microbiology_lab_accessories",
      description: "Disposable calibrated 10 uL inoculating loops, sterile, 1000/box (Demo).",
      status: "active",
    },
  ];

  const productFormats: ProductFormat[] = [
    { ...ctx.canonical(FORMATS.granulated), name: "Granulated dehydrated powder (Demo)", form: "granulated" },
    { ...ctx.canonical(FORMATS.readyPlate), name: "Ready-to-use 90 mm plate (Demo)", form: "ready_plate" },
    { ...ctx.canonical(FORMATS.pellet), name: "Lyophilized QC pellet (Demo)", form: "other" },
    { ...ctx.canonical(FORMATS.instrument), name: "Benchtop instrument (Demo)", form: "instrument" },
    { ...ctx.canonical(FORMATS.canister), name: "Sterility test canister (Demo)", form: "consumable" },
  ];

  const skus: Sku[] = [
    {
      ...ctx.canonical(SKUS.tsa500),
      productId: PRODUCTS.tsaAcme,
      catalogueNumber: "ACM-1058.0500",
      manufacturerCode: "1058",
      name: "TSA dehydrated medium 500 g (Demo)",
      alternateNames: ["TSA powder (Demo)", "Tryptic Soy Agar 500 g (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN", "SG", "KH"],
      status: "active",
    },
    {
      // Near-duplicate of SKUS.tsa500 created by a spreadsheet import: same
      // catalogue number, slightly different name, no commercial coverage.
      ...ctx.canonical(SKUS.tsa500Dup),
      productId: PRODUCTS.tsaAcme,
      catalogueNumber: "ACM-1058.0500",
      name: "TSA dehydrated medium 500 g bottle (Demo)",
      alternateNames: ["TSA 500g import (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.tsaPlates20),
      productId: PRODUCTS.tsaPlatesAcme,
      catalogueNumber: "ACM-P2001",
      name: "TSA ready plates 90 mm 20/pack (Demo)",
      alternateNames: ["TSA ready-to-use plates (Demo)"],
      formatId: FORMATS.readyPlate,
      shelfLifeMonths: 6,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.nb500),
      productId: PRODUCTS.nbAcme,
      catalogueNumber: "ACM-1002.0500",
      name: "Nutrient Broth dehydrated medium 500 g (Demo)",
      alternateNames: [],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN", "SG"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.tsaDelta500),
      productId: PRODUCTS.tsaDelta,
      catalogueNumber: "DBS-5001.0500",
      name: "Tryptic Soy Agar dehydrated medium 500 g (Demo)",
      alternateNames: ["DeltaBio TSA 500 g (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN", "TH"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.sdaPlates20),
      productId: PRODUCTS.sdaPlatesDelta,
      catalogueNumber: "DBS-P3301",
      name: "SDA ready plates 90 mm 20/pack (Demo)",
      alternateNames: ["Sabouraud plates (Demo)"],
      formatId: FORMATS.readyPlate,
      shelfLifeMonths: 4,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.qcBsub10),
      productId: PRODUCTS.qcDelta,
      catalogueNumber: "DBS-Q6633",
      name: "B. subtilis ATCC 6633 QC pellets 10/pack (Demo)",
      alternateNames: ["DeltaSeed B. subtilis (Demo)"],
      formatId: FORMATS.pellet,
      shelfLifeMonths: 24,
      storageCondition: "-20 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      // Discontinued competitor SKU with a successor.
      ...ctx.canonical(SKUS.naOld500),
      productId: PRODUCTS.naDeltaOld,
      catalogueNumber: "DBS-1007.0500",
      name: "Nutrient Agar legacy 500 g (Demo)",
      alternateNames: [],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "discontinued",
      successorSkuId: SKUS.na2x500,
    },
    {
      ...ctx.canonical(SKUS.na2x500),
      productId: PRODUCTS.naDelta,
      catalogueNumber: "DBS-1107.0500",
      name: "Nutrient Agar NA-2 500 g (Demo)",
      alternateNames: [],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.airAs100),
      productId: PRODUCTS.airCondor,
      catalogueNumber: "CLW-AS100",
      name: "AirSampler AS-100 100 L/min (Demo)",
      alternateNames: ["Condor air sampler (Demo)"],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.emContact20),
      productId: PRODUCTS.emCondor,
      catalogueNumber: "CLW-EC20",
      name: "AS-100 contact plates ready 20/pack (Demo)",
      alternateNames: ["Condor contact plates (Demo)"],
      formatId: FORMATS.readyPlate,
      shelfLifeMonths: 6,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.pc50),
      productId: PRODUCTS.pcCondor,
      catalogueNumber: "CLW-PC50",
      name: "CondorCount PC-50 0.3 um particle counter (Demo)",
      alternateNames: [],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.steriCan10),
      productId: PRODUCTS.steriCondor,
      catalogueNumber: "CLW-ST110",
      name: "SteriCan canisters 10/box (Demo)",
      alternateNames: [],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.cc500),
      productId: PRODUCTS.ccAurora,
      catalogueNumber: "ABW-C200.0500",
      name: "AuroraChrom Coliform Agar 500 g (Demo)",
      alternateNames: ["CCA chromogenic agar (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN", "KR"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.ccPlates20),
      productId: PRODUCTS.ccPlatesAurora,
      catalogueNumber: "ABW-P5510",
      name: "AuroraChrom Listeria plates 90 mm 20/pack (Demo)",
      alternateNames: ["Listeria chromogenic plates (Demo)"],
      formatId: FORMATS.readyPlate,
      shelfLifeMonths: 4,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.st200),
      productId: PRODUCTS.st200Condor,
      catalogueNumber: "CLW-ST200",
      name: "SteriTest ST-200 pump unit (Demo)",
      alternateNames: ["Condor closed sterility testing system (Demo)"],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.sp3000),
      productId: PRODUCTS.sp3000Meridian,
      catalogueNumber: "MLS-SP3000",
      name: "SteriPump SP-3000 pump unit (Demo)",
      alternateNames: ["Meridian closed sterility testing system (Demo)"],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.ag90),
      productId: PRODUCTS.ag90Meridian,
      catalogueNumber: "MLS-AG90",
      name: "AirGuard AG-90 90 L/min air sampler (Demo)",
      alternateNames: ["Meridian air sampler (Demo)"],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.pc90),
      productId: PRODUCTS.pc90Meridian,
      catalogueNumber: "MLS-PC90",
      name: "PartiCount PC-90 handheld 0.3 um (Demo)",
      alternateNames: [],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.biGst100),
      productId: PRODUCTS.biDelta,
      catalogueNumber: "DBS-B12980",
      name: "G. stearothermophilus ATCC 12980 spore strips 100/box (Demo)",
      alternateNames: ["Steam BI spore strips (Demo)"],
      formatId: FORMATS.pellet,
      shelfLifeMonths: 18,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.biAmp20),
      productId: PRODUCTS.biSteriSure,
      catalogueNumber: "MLS-BI20",
      name: "SteriSure BI ampoules 20/box (Demo)",
      alternateNames: ["Self-contained biological indicators (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.choMax10),
      productId: PRODUCTS.choMaxNovara,
      catalogueNumber: "NBP-CM100",
      name: "CHO-Max basal medium powder 10 L (Demo)",
      alternateNames: ["CHO basal medium (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 24,
      storageCondition: "2-8 °C, dry",
      countryAvailability: ["VN", "SG"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.feed1l),
      productId: PRODUCTS.feedDelta,
      catalogueNumber: "DBS-F2100",
      name: "DeltaGrow CHO feed 1 L (Demo)",
      alternateNames: [],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 18,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.etoh20l),
      productId: PRODUCTS.etohVesta,
      catalogueNumber: "VCH-E9620",
      name: "Ethanol 96% USP 20 L drum (Demo)",
      alternateNames: ["USP ethanol (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 36,
      storageCondition: "ambient, flammable store",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.pbs5l),
      productId: PRODUCTS.pbsNovara,
      catalogueNumber: "NBP-PBS05",
      name: "PBS concentrate 10x 5 L (Demo)",
      alternateNames: [],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.proa1l),
      productId: PRODUCTS.proaAuriga,
      catalogueNumber: "AGS-PA1000",
      name: "AuriSelect Protein A resin 1 L (Demo)",
      alternateNames: ["Protein A resin (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "2-8 °C, 20% ethanol",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.qmem10),
      productId: PRODUCTS.qKestrel,
      catalogueNumber: "KFL-QM010",
      name: "Q membrane capsules 10/pack (Demo)",
      alternateNames: [],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.steriFlow3),
      productId: PRODUCTS.steriFlowKestrel,
      catalogueNumber: "KFL-SF022",
      name: "SteriFlow 0.22 um cartridges 3/pack (Demo)",
      alternateNames: ["Sterilizing-grade filter (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.tff30k),
      productId: PRODUCTS.tffAuriga,
      catalogueNumber: "AGS-TFF30",
      name: "AuriFlow TFF cassette 30 kDa 0.1 m2 (Demo)",
      alternateNames: [],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient, wet",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.endoZyme192),
      productId: PRODUCTS.endoZymeOrizon,
      catalogueNumber: "OBA-RFC192",
      name: "EndoZyme rFC kit 192 tests (Demo)",
      alternateNames: ["Recombinant Factor C assay (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 18,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.lalCart50),
      productId: PRODUCTS.lalDelta,
      catalogueNumber: "DBS-LAL050",
      name: "LAL gel-clot cartridges 50 tests (Demo)",
      alternateNames: ["LAL cartridges (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.spCan10),
      productId: PRODUCTS.spCanMeridian,
      catalogueNumber: "MLS-SPC10",
      name: "SteriPump closed canisters 10/box (Demo)",
      alternateNames: ["Meridian sterility canisters (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.dcp20),
      productId: PRODUCTS.dcpDelta,
      catalogueNumber: "DBS-P5520",
      name: "DeltaPlate contact plates 55 mm 20/pack (Demo)",
      alternateNames: ["Delta contact plates (Demo)"],
      formatId: FORMATS.readyPlate,
      shelfLifeMonths: 6,
      storageCondition: "2-8 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.qcEcoli10),
      productId: PRODUCTS.qcEcoliOrizon,
      catalogueNumber: "OBA-Q8739",
      name: "E. coli ATCC 8739 QC pellets 10/pack (Demo)",
      alternateNames: ["OrizonQC E. coli (Demo)"],
      formatId: FORMATS.pellet,
      shelfLifeMonths: 24,
      storageCondition: "-20 °C",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.turntable),
      productId: PRODUCTS.turntableCondor,
      catalogueNumber: "CLW-PT01",
      name: "PetriTurn plate turntable (Demo)",
      alternateNames: [],
      formatId: FORMATS.instrument,
      storageCondition: "ambient",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.loops1000),
      productId: PRODUCTS.loopsMeridian,
      catalogueNumber: "MLS-LP10",
      name: "Inoculating loops 10 uL sterile 1000/box (Demo)",
      alternateNames: ["Sterile loops (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    // -- Pack-size variants: same product, different pack economics -------------
    {
      ...ctx.canonical(SKUS.tsa100),
      productId: PRODUCTS.tsaAcme,
      catalogueNumber: "ACM-1058.0100",
      name: "TSA dehydrated medium 100 g (Demo)",
      alternateNames: ["TSA 100 g trial size (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.tsa5kg),
      productId: PRODUCTS.tsaAcme,
      catalogueNumber: "ACM-1058.5000",
      name: "TSA dehydrated medium 5 kg (Demo)",
      alternateNames: ["TSA 5 kg bulk (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 36,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.choMax100),
      productId: PRODUCTS.choMaxNovara,
      catalogueNumber: "NBP-CM1100",
      name: "CHO-Max basal medium powder 100 L (Demo)",
      alternateNames: ["CHO-Max process scale (Demo)"],
      formatId: FORMATS.granulated,
      shelfLifeMonths: 24,
      storageCondition: "2-8 °C, dry",
      countryAvailability: ["VN", "SG"],
      status: "active",
    },
    {
      ...ctx.canonical(SKUS.steriCan50),
      productId: PRODUCTS.steriCondor,
      catalogueNumber: "CLW-ST150",
      name: "SteriCan canisters 50/box (Demo)",
      alternateNames: ["SteriCan bulk box (Demo)"],
      formatId: FORMATS.canister,
      shelfLifeMonths: 24,
      storageCondition: "ambient, dry",
      countryAvailability: ["VN"],
      status: "active",
    },
  ];

  const packConfigurations: PackConfiguration[] = [
    { ...ctx.canonical(PACKS.tsa500), skuId: SKUS.tsa500, quantity: 500, unit: "g", description: "500 g bottle" },
    { ...ctx.canonical(PACKS.tsaPlates20), skuId: SKUS.tsaPlates20, quantity: 20, unit: "plate", unitsPerPack: 20, description: "90 mm plates, 20 per pack" },
    { ...ctx.canonical(PACKS.nb500), skuId: SKUS.nb500, quantity: 500, unit: "g", description: "500 g bottle" },
    { ...ctx.canonical(PACKS.tsaDelta500), skuId: SKUS.tsaDelta500, quantity: 500, unit: "g", description: "500 g bottle" },
    { ...ctx.canonical(PACKS.sda20), skuId: SKUS.sdaPlates20, quantity: 20, unit: "plate", unitsPerPack: 20, description: "90 mm plates, 20 per pack" },
    { ...ctx.canonical(PACKS.qcBsub10), skuId: SKUS.qcBsub10, quantity: 1, unit: "pack", unitsPerPack: 10, description: "10 pellets per pack" },
    { ...ctx.canonical(PACKS.na2x500), skuId: SKUS.na2x500, quantity: 500, unit: "g", description: "500 g bottle" },
    { ...ctx.canonical(PACKS.emContact20), skuId: SKUS.emContact20, quantity: 20, unit: "plate", unitsPerPack: 20, description: "Contact plates, 20 per pack" },
    { ...ctx.canonical(PACKS.steri10), skuId: SKUS.steriCan10, quantity: 1, unit: "box", unitsPerPack: 10, description: "10 canisters per box" },
    { ...ctx.canonical(PACKS.airAs100), skuId: SKUS.airAs100, quantity: 1, unit: "unit", description: "One instrument" },
    { ...ctx.canonical(PACKS.pc50), skuId: SKUS.pc50, quantity: 1, unit: "unit", description: "One instrument" },
    { ...ctx.canonical(PACKS.cc500), skuId: SKUS.cc500, quantity: 500, unit: "g", description: "500 g bottle" },
    { ...ctx.canonical(PACKS.ccPlates20), skuId: SKUS.ccPlates20, quantity: 20, unit: "plate", unitsPerPack: 20, description: "90 mm plates, 20 per pack" },
    { ...ctx.canonical(PACKS.st200), skuId: SKUS.st200, quantity: 1, unit: "unit", description: "One pump unit" },
    { ...ctx.canonical(PACKS.sp3000), skuId: SKUS.sp3000, quantity: 1, unit: "unit", description: "One pump unit" },
    { ...ctx.canonical(PACKS.ag90), skuId: SKUS.ag90, quantity: 1, unit: "unit", description: "One instrument" },
    { ...ctx.canonical(PACKS.pc90), skuId: SKUS.pc90, quantity: 1, unit: "unit", description: "One instrument" },
    { ...ctx.canonical(PACKS.biGst100), skuId: SKUS.biGst100, quantity: 1, unit: "box", unitsPerPack: 100, description: "100 spore strips per box" },
    { ...ctx.canonical(PACKS.biAmp20), skuId: SKUS.biAmp20, quantity: 1, unit: "box", unitsPerPack: 20, description: "20 ampoules per box" },
    { ...ctx.canonical(PACKS.choMax10), skuId: SKUS.choMax10, quantity: 10, unit: "L", description: "Powder for 10 L of medium" },
    { ...ctx.canonical(PACKS.feed1l), skuId: SKUS.feed1l, quantity: 1, unit: "L", description: "1 L bottle" },
    { ...ctx.canonical(PACKS.etoh20l), skuId: SKUS.etoh20l, quantity: 20, unit: "L", description: "20 L drum" },
    { ...ctx.canonical(PACKS.pbs5l), skuId: SKUS.pbs5l, quantity: 5, unit: "L", description: "5 L jerrycan" },
    { ...ctx.canonical(PACKS.proa1l), skuId: SKUS.proa1l, quantity: 1, unit: "L", description: "1 L settled resin" },
    { ...ctx.canonical(PACKS.qmem10), skuId: SKUS.qmem10, quantity: 1, unit: "pack", unitsPerPack: 10, description: "10 capsules per pack" },
    { ...ctx.canonical(PACKS.steriFlow3), skuId: SKUS.steriFlow3, quantity: 1, unit: "pack", unitsPerPack: 3, description: "3 cartridges per pack" },
    { ...ctx.canonical(PACKS.tff30k), skuId: SKUS.tff30k, quantity: 1, unit: "unit", description: "One cassette, 0.1 m2" },
    { ...ctx.canonical(PACKS.endoZyme192), skuId: SKUS.endoZyme192, quantity: 192, unit: "test", description: "Kit for 192 tests" },
    { ...ctx.canonical(PACKS.lalCart50), skuId: SKUS.lalCart50, quantity: 50, unit: "test", description: "50 cartridges per kit" },
    { ...ctx.canonical(PACKS.spCan10), skuId: SKUS.spCan10, quantity: 1, unit: "box", unitsPerPack: 10, description: "10 canisters per box" },
    { ...ctx.canonical(PACKS.dcp20), skuId: SKUS.dcp20, quantity: 20, unit: "plate", unitsPerPack: 20, description: "55 mm contact plates, 20 per pack" },
    { ...ctx.canonical(PACKS.qcEcoli10), skuId: SKUS.qcEcoli10, quantity: 1, unit: "pack", unitsPerPack: 10, description: "10 pellets per pack" },
    { ...ctx.canonical(PACKS.turntable), skuId: SKUS.turntable, quantity: 1, unit: "unit", description: "One turntable" },
    { ...ctx.canonical(PACKS.loops1000), skuId: SKUS.loops1000, quantity: 1, unit: "box", unitsPerPack: 1000, description: "1000 loops per box" },
    { ...ctx.canonical(PACKS.tsa100), skuId: SKUS.tsa100, quantity: 100, unit: "g", description: "100 g bottle" },
    { ...ctx.canonical(PACKS.tsa5kg), skuId: SKUS.tsa5kg, quantity: 5, unit: "kg", description: "5 kg pail" },
    { ...ctx.canonical(PACKS.choMax100), skuId: SKUS.choMax100, quantity: 100, unit: "L", description: "Powder for 100 L of medium" },
    { ...ctx.canonical(PACKS.steriCan50), skuId: SKUS.steriCan50, quantity: 1, unit: "box", unitsPerPack: 50, description: "50 canisters per box" },
  ];

  const productDocuments: ProductDocument[] = [
    {
      ...ctx.canonical("pdoc-tsa-tds"),
      skuId: SKUS.tsa500,
      docType: "tds",
      title: "TSA Technical Data Sheet (Demo)",
      sourceId: SOURCES.acmeCatalogue,
    },
    {
      ...ctx.canonical("pdoc-tsa-coa"),
      skuId: SKUS.tsa500,
      docType: "coa",
      title: "TSA Certificate of Analysis template (Demo)",
      sourceId: SOURCES.acmeCatalogue,
    },
    {
      ...ctx.canonical("pdoc-tp-ifu"),
      skuId: SKUS.tsaPlates20,
      docType: "instruction",
      title: "TSA ready plates instructions for use (Demo)",
      sourceId: SOURCES.acmeWebsite,
    },
    {
      ...ctx.canonical("pdoc-as100-manual"),
      productId: PRODUCTS.airCondor,
      docType: "instruction",
      title: "AirSampler AS-100 user manual (Demo)",
      sourceId: SOURCES.condorCatalogue,
    },
    {
      ...ctx.canonical("pdoc-cc-tds"),
      skuId: SKUS.cc500,
      docType: "tds",
      title: "AuroraChrom Coliform Agar Technical Data Sheet (Demo)",
      sourceId: SOURCES.auroraCatalogue,
    },
    {
      ...ctx.canonical("pdoc-ccp-ifu"),
      skuId: SKUS.ccPlates20,
      docType: "instruction",
      title: "AuroraChrom Listeria plates instructions for use (Demo)",
      sourceId: SOURCES.auroraCatalogue,
    },
    {
      ...ctx.canonical("pdoc-st200-manual"),
      skuId: SKUS.st200,
      docType: "instruction",
      title: "SteriTest ST-200 user manual (Demo)",
      sourceId: SOURCES.condorCatalogue,
    },
    {
      ...ctx.canonical("pdoc-sp3000-manual"),
      skuId: SKUS.sp3000,
      docType: "instruction",
      title: "SteriPump SP-3000 user manual (Demo)",
      sourceId: SOURCES.meridianCatalogue,
    },
    {
      ...ctx.canonical("pdoc-ag90-manual"),
      skuId: SKUS.ag90,
      docType: "instruction",
      title: "AirGuard AG-90 user manual (Demo)",
      sourceId: SOURCES.meridianCatalogue,
    },
    {
      ...ctx.canonical("pdoc-bi-gst-tds"),
      skuId: SKUS.biGst100,
      docType: "tds",
      title: "DeltaSeed spore strips technical data sheet (Demo)",
      sourceId: SOURCES.deltaCatalogue,
    },
    {
      ...ctx.canonical("pdoc-chomax-tds"),
      skuId: SKUS.choMax10,
      docType: "tds",
      title: "CHO-Max basal medium technical data sheet (Demo)",
      sourceId: SOURCES.novaraCatalogue,
    },
    {
      ...ctx.canonical("pdoc-proa-tds"),
      skuId: SKUS.proa1l,
      docType: "tds",
      title: "AuriSelect Protein A resin technical data sheet (Demo)",
      sourceId: SOURCES.aurigaCatalogue,
    },
    {
      ...ctx.canonical("pdoc-endozyme-ifu"),
      skuId: SKUS.endoZyme192,
      docType: "instruction",
      title: "EndoZyme rFC kit instructions for use (Demo)",
      sourceId: SOURCES.orizonCatalogue,
    },
    {
      ...ctx.canonical("pdoc-etoh-coa"),
      skuId: SKUS.etoh20l,
      docType: "coa",
      title: "VestaPure ethanol certificate of analysis template (Demo)",
      sourceId: SOURCES.vestaCatalogue,
    },
    {
      ...ctx.canonical("pdoc-etoh-msds"),
      skuId: SKUS.etoh20l,
      docType: "msds",
      title: "VestaPure ethanol 96% safety data sheet (Demo)",
      sourceId: SOURCES.vestaCatalogue,
    },
    {
      ...ctx.canonical("pdoc-proa-coa"),
      skuId: SKUS.proa1l,
      docType: "coa",
      title: "AuriSelect Protein A resin certificate of analysis template (Demo)",
      sourceId: SOURCES.aurigaCatalogue,
    },
    {
      ...ctx.canonical("pdoc-steriflow-cert"),
      skuId: SKUS.steriFlow3,
      docType: "certificate",
      title: "SteriFlow cartridges bacterial retention certificate (Demo)",
      sourceId: SOURCES.kestrelCatalogue,
    },
    {
      ...ctx.canonical("pdoc-chomax-msds"),
      skuId: SKUS.choMax10,
      docType: "msds",
      title: "CHO-Max basal medium safety data sheet (Demo)",
      sourceId: SOURCES.novaraCatalogue,
    },
    {
      ...ctx.canonical("pdoc-qcecoli-coa"),
      skuId: SKUS.qcEcoli10,
      docType: "coa",
      title: "OrizonQC pellets certificate of analysis template (Demo)",
      sourceId: SOURCES.orizonCatalogue,
    },
  ];

  // -- Scientific / regulatory reference entities ------------------------------
  // Generic reference names are real public-fact-like terms; the records
  // themselves are still synthetic (isDemo: true).
  const applications: Application[] = [
    { ...ctx.canonical(APPLICATIONS.sterilityTesting), name: "Sterility testing", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.microbialLimits), name: "Microbial limits testing", industryCodes: ["pharma", "food_beverage"] },
    { ...ctx.canonical(APPLICATIONS.envMonitoring), name: "Environmental monitoring", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.growthPromotion), name: "Growth promotion testing", industryCodes: ["pharma", "food_beverage"] },
    { ...ctx.canonical(APPLICATIONS.mediaFill), name: "Media fill trials", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.pathogenDetection), name: "Pathogen detection", industryCodes: ["food_beverage"] },
    { ...ctx.canonical(APPLICATIONS.sterilizationValidation), name: "Sterilization validation", industryCodes: ["pharma", "food_beverage"] },
    { ...ctx.canonical(APPLICATIONS.upstreamCellCulture), name: "Upstream cell culture", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.apiSynthesis), name: "API synthesis", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.downstreamPurification), name: "Downstream purification", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.endotoxinTesting), name: "Endotoxin testing", industryCodes: ["pharma"] },
    { ...ctx.canonical(APPLICATIONS.sterileFiltration), name: "Sterile filtration", industryCodes: ["pharma"] },
  ];

  const methods: Method[] = [
    {
      ...ctx.canonical(METHODS.membraneFiltration),
      name: "Membrane filtration",
      description: "Filtration-based sterility and bioburden method (Demo).",
      standardIds: [STANDARDS.usp71],
    },
    {
      ...ctx.canonical(METHODS.plateCount),
      name: "Plate count method",
      description: "Pour-plate / spread-plate enumeration (Demo).",
      standardIds: [STANDARDS.iso11133],
    },
    {
      ...ctx.canonical(METHODS.affinityChromatography),
      name: "Affinity chromatography",
      description: "Protein A / ligand-based capture chromatography (Demo).",
      standardIds: [],
    },
  ];

  const standards: Standard[] = [
    {
      ...ctx.canonical(STANDARDS.iso11133),
      body: "ISO",
      code: "11133",
      title: "Microbiology of the food chain — Preparation, production, storage and performance testing of culture media",
    },
    {
      ...ctx.canonical(STANDARDS.iso17025),
      body: "ISO",
      code: "17025",
      title: "General requirements for the competence of testing and calibration laboratories",
    },
    {
      ...ctx.canonical(STANDARDS.usp61),
      body: "USP",
      code: "61",
      title: "Microbiological Examination of Nonsterile Products: Microbial Enumeration Tests",
    },
    {
      ...ctx.canonical(STANDARDS.usp71),
      body: "USP",
      code: "71",
      title: "Sterility Tests",
    },
    {
      // Fictional TCVN code — clearly a demo standard.
      ...ctx.canonical(STANDARDS.tcvnDemo),
      body: "TCVN",
      code: "9999",
      title: "Culture media for industrial microbiology — Demo specification",
    },
    {
      ...ctx.canonical(STANDARDS.iso6579),
      body: "ISO",
      code: "6579-1",
      title: "Microbiology of the food chain — Horizontal method for the detection, enumeration and serotyping of Salmonella",
    },
    {
      ...ctx.canonical(STANDARDS.iso11290),
      body: "ISO",
      code: "11290-1",
      title: "Microbiology of the food chain — Horizontal method for the detection and enumeration of Listeria monocytogenes",
    },
    {
      ...ctx.canonical(STANDARDS.iso11138),
      body: "ISO",
      code: "11138-1",
      title: "Sterilization of health care products — Biological indicators — General requirements",
    },
    {
      ...ctx.canonical(STANDARDS.usp85),
      body: "USP",
      code: "85",
      title: "Bacterial Endotoxins Test",
    },
  ];

  const standardVersions: StandardVersion[] = [
    { ...ctx.canonical(STANDARD_VERSIONS.iso11133v2014), standardId: STANDARDS.iso11133, version: "2014", year: 2014, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.iso17025v2017), standardId: STANDARDS.iso17025, version: "2017", year: 2017, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.usp61v2024), standardId: STANDARDS.usp61, version: "2024", year: 2024, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.usp71v2024), standardId: STANDARDS.usp71, version: "2024", year: 2024, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.tcvnV2025), standardId: STANDARDS.tcvnDemo, version: "2025", year: 2025, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.iso6579v2017), standardId: STANDARDS.iso6579, version: "2017", year: 2017, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.iso11290v2017), standardId: STANDARDS.iso11290, version: "2017", year: 2017, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.iso11138v2017), standardId: STANDARDS.iso11138, version: "2017", year: 2017, status: "current" },
    { ...ctx.canonical(STANDARD_VERSIONS.usp85v2024), standardId: STANDARDS.usp85, version: "2024", year: 2024, status: "current" },
  ];

  const organisms: Organism[] = [
    { ...ctx.canonical(ORGANISMS.bsub), genus: "Bacillus", species: "subtilis", strainCode: "ATCC 6633", gramReaction: "positive" },
    { ...ctx.canonical(ORGANISMS.ecoli), genus: "Escherichia", species: "coli", strainCode: "ATCC 8739", gramReaction: "negative" },
    { ...ctx.canonical(ORGANISMS.saur), genus: "Staphylococcus", species: "aureus", strainCode: "ATCC 6538", gramReaction: "positive" },
    { ...ctx.canonical(ORGANISMS.paer), genus: "Pseudomonas", species: "aeruginosa", strainCode: "ATCC 9027", gramReaction: "negative" },
    { ...ctx.canonical(ORGANISMS.calb), genus: "Candida", species: "albicans", strainCode: "ATCC 10231", gramReaction: "variable" },
    { ...ctx.canonical(ORGANISMS.listeria), genus: "Listeria", species: "monocytogenes", strainCode: "ATCC 13932", gramReaction: "positive" },
    { ...ctx.canonical(ORGANISMS.salmonella), genus: "Salmonella", species: "enterica", strainCode: "ATCC 14028", gramReaction: "negative" },
    { ...ctx.canonical(ORGANISMS.gstearo), genus: "Geobacillus", species: "stearothermophilus", strainCode: "ATCC 12980", gramReaction: "positive" },
  ];

  const sampleTypes: SampleType[] = [
    { ...ctx.canonical(SAMPLE_TYPES.water), name: "Purified water" },
    { ...ctx.canonical(SAMPLE_TYPES.air), name: "Air (ambient / compressed)" },
    { ...ctx.canonical(SAMPLE_TYPES.surface), name: "Surface swab" },
    { ...ctx.canonical(SAMPLE_TYPES.rawMaterial), name: "Raw material" },
    { ...ctx.canonical(SAMPLE_TYPES.milk), name: "Raw milk" },
    { ...ctx.canonical(SAMPLE_TYPES.cellCultureBroth), name: "Cell culture broth / harvest" },
    { ...ctx.canonical(SAMPLE_TYPES.bulkDrugSubstance), name: "Bulk drug substance" },
  ];

  const industries: Industry[] = [
    { ...ctx.canonical(INDUSTRIES.pharma), code: "pharma", name: "Pharmaceuticals" },
    { ...ctx.canonical(INDUSTRIES.food), code: "food_beverage", name: "Food & beverage" },
  ];

  const testTypes: TestType[] = [
    { ...ctx.canonical(TEST_TYPES.bioburden), name: "Bioburden" },
    { ...ctx.canonical(TEST_TYPES.sterilityTest), name: "Sterility test" },
    { ...ctx.canonical(TEST_TYPES.endotoxinTest), name: "Bacterial endotoxins test" },
  ];

  const incubationConditions: IncubationCondition[] = [
    {
      ...ctx.canonical(INCUBATION.aerobic3035),
      temperatureCelsius: 32.5,
      durationHours: 72,
      atmosphere: "aerobic",
      description: "30-35 °C, 3 days, aerobic (Demo)",
    },
  ];

  const preparationMethods: PreparationMethod[] = [
    {
      ...ctx.canonical(PREPARATION.autoclave),
      name: "Autoclave 121 °C 15 min (Demo)",
      description: "Standard moist-heat sterilization of dehydrated media (Demo).",
    },
  ];

  // -- Evidence-carrying product edges ------------------------------------------
  const e = edgeEvidence;
  const productEdges: ProductEdge[] = [
    // TSA dehydrated (Acme) — the richest node in the graph.
    { ...ctx.canonical("edge-tsa-app-limits"), productId: PRODUCTS.tsaAcme, targetType: "application", targetId: APPLICATIONS.microbialLimits, role: "intended_use", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-app-em"), productId: PRODUCTS.tsaAcme, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-app-gpt"), productId: PRODUCTS.tsaAcme, targetType: "application", targetId: APPLICATIONS.growthPromotion, role: "intended_use", evidence: e(SOURCES.acmeCatalogue, "analyst_reviewed", 0.9) },
    { ...ctx.canonical("edge-tsa-std-11133"), productId: PRODUCTS.tsaAcme, targetType: "standard", targetId: STANDARDS.iso11133, role: "conforms_to", evidence: e(SOURCES.iso11133, "source_captured", 0.95) },
    { ...ctx.canonical("edge-tsa-std-usp61"), productId: PRODUCTS.tsaAcme, targetType: "standard", targetId: STANDARDS.usp61, role: "conforms_to", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tsa-std-tcvn"), productId: PRODUCTS.tsaAcme, targetType: "standard", targetId: STANDARDS.tcvnDemo, role: "conforms_to", evidence: e(SOURCES.internalNote, "unverified", 0.4) },
    { ...ctx.canonical("edge-tsa-orgm-ecoli"), productId: PRODUCTS.tsaAcme, targetType: "organism", targetId: ORGANISMS.ecoli, role: "growth_promotion", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-orgm-saur"), productId: PRODUCTS.tsaAcme, targetType: "organism", targetId: ORGANISMS.saur, role: "growth_promotion", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-orgm-bsub"), productId: PRODUCTS.tsaAcme, targetType: "organism", targetId: ORGANISMS.bsub, role: "growth_promotion", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-orgm-paer"), productId: PRODUCTS.tsaAcme, targetType: "organism", targetId: ORGANISMS.paer, role: "growth_promotion", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tsa-smp-water"), productId: PRODUCTS.tsaAcme, targetType: "sample_type", targetId: SAMPLE_TYPES.water, role: "sample_type", evidence: e(SOURCES.internalNote, "unverified", 0.4) },
    { ...ctx.canonical("edge-tsa-ind-pharma"), productId: PRODUCTS.tsaAcme, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tsa-ind-food"), productId: PRODUCTS.tsaAcme, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tsa-prep"), productId: PRODUCTS.tsaAcme, targetType: "preparation_method", targetId: PREPARATION.autoclave, role: "preparation", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.9) },
    // TSA ready plates (Acme)
    { ...ctx.canonical("edge-tp-app-em"), productId: PRODUCTS.tsaPlatesAcme, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.acmeWebsite, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tp-std-11133"), productId: PRODUCTS.tsaPlatesAcme, targetType: "standard", targetId: STANDARDS.iso11133, role: "conforms_to", evidence: e(SOURCES.iso11133, "source_captured", 0.9) },
    { ...ctx.canonical("edge-tp-ind-pharma"), productId: PRODUCTS.tsaPlatesAcme, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.acmeWebsite, "source_captured", 0.8) },
    { ...ctx.canonical("edge-tp-inc"), productId: PRODUCTS.tsaPlatesAcme, targetType: "incubation_condition", targetId: INCUBATION.aerobic3035, role: "incubation", evidence: e(SOURCES.acmeWebsite, "source_captured", 0.8) },
    // TSA dehydrated (DeltaBio) — thinner evidence on purpose.
    { ...ctx.canonical("edge-td-app-limits"), productId: PRODUCTS.tsaDelta, targetType: "application", targetId: APPLICATIONS.microbialLimits, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-td-std-11133"), productId: PRODUCTS.tsaDelta, targetType: "standard", targetId: STANDARDS.iso11133, role: "conforms_to", evidence: e(SOURCES.deltaCatalogue, "unverified", 0.5) },
    { ...ctx.canonical("edge-td-ind-pharma"), productId: PRODUCTS.tsaDelta, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    // SDA ready plates (DeltaBio)
    { ...ctx.canonical("edge-sda-app-em"), productId: PRODUCTS.sdaPlatesDelta, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-sda-orgm-calb"), productId: PRODUCTS.sdaPlatesDelta, targetType: "organism", targetId: ORGANISMS.calb, role: "growth_promotion", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-sda-std-11133"), productId: PRODUCTS.sdaPlatesDelta, targetType: "standard", targetId: STANDARDS.iso11133, role: "conforms_to", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    // QC pellets (DeltaBio)
    { ...ctx.canonical("edge-qc-orgm-bsub"), productId: PRODUCTS.qcDelta, targetType: "organism", targetId: ORGANISMS.bsub, role: "qc_test_strain", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.95) },
    { ...ctx.canonical("edge-qc-app-gpt"), productId: PRODUCTS.qcDelta, targetType: "application", targetId: APPLICATIONS.growthPromotion, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-qc-std-17025"), productId: PRODUCTS.qcDelta, targetType: "standard", targetId: STANDARDS.iso17025, role: "supports", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.7) },
    // EM consumables (Condor)
    { ...ctx.canonical("edge-em-app-em"), productId: PRODUCTS.emCondor, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-em-tt-bioburden"), productId: PRODUCTS.emCondor, targetType: "test_type", targetId: TEST_TYPES.bioburden, role: "test_type", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-em-smp-air"), productId: PRODUCTS.emCondor, targetType: "sample_type", targetId: SAMPLE_TYPES.air, role: "sample_type", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-em-smp-surface"), productId: PRODUCTS.emCondor, targetType: "sample_type", targetId: SAMPLE_TYPES.surface, role: "sample_type", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.8) },
    // Sterility canisters (Condor)
    { ...ctx.canonical("edge-st-app-sterility"), productId: PRODUCTS.steriCondor, targetType: "application", targetId: APPLICATIONS.sterilityTesting, role: "intended_use", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-st-std-usp71"), productId: PRODUCTS.steriCondor, targetType: "standard", targetId: STANDARDS.usp71, role: "conforms_to", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-st-mth-membrane"), productId: PRODUCTS.steriCondor, targetType: "method", targetId: METHODS.membraneFiltration, role: "method", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    // Nutrient Broth (Acme) — food industry angle.
    { ...ctx.canonical("edge-nb-app-limits"), productId: PRODUCTS.nbAcme, targetType: "application", targetId: APPLICATIONS.microbialLimits, role: "intended_use", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-nb-ind-food"), productId: PRODUCTS.nbAcme, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.acmeCatalogue, "source_captured", 0.8) },
    // AuroraChrom Coliform Agar (Aurora) — dairy pathogen screening.
    { ...ctx.canonical("edge-cc-app-pathogen"), productId: PRODUCTS.ccAurora, targetType: "application", targetId: APPLICATIONS.pathogenDetection, role: "intended_use", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-cc-app-limits"), productId: PRODUCTS.ccAurora, targetType: "application", targetId: APPLICATIONS.microbialLimits, role: "intended_use", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-cc-orgm-ecoli"), productId: PRODUCTS.ccAurora, targetType: "organism", targetId: ORGANISMS.ecoli, role: "detection", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-cc-std-6579"), productId: PRODUCTS.ccAurora, targetType: "standard", targetId: STANDARDS.iso6579, role: "conforms_to", evidence: e(SOURCES.auroraCatalogue, "unverified", 0.5) },
    { ...ctx.canonical("edge-cc-ind-food"), productId: PRODUCTS.ccAurora, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-cc-smp-milk"), productId: PRODUCTS.ccAurora, targetType: "sample_type", targetId: SAMPLE_TYPES.milk, role: "sample_type", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-cc-prep"), productId: PRODUCTS.ccAurora, targetType: "preparation_method", targetId: PREPARATION.autoclave, role: "preparation", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.85) },
    // AuroraChrom Listeria ready plates (Aurora)
    { ...ctx.canonical("edge-ccp-app-pathogen"), productId: PRODUCTS.ccPlatesAurora, targetType: "application", targetId: APPLICATIONS.pathogenDetection, role: "intended_use", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-ccp-orgm-listeria"), productId: PRODUCTS.ccPlatesAurora, targetType: "organism", targetId: ORGANISMS.listeria, role: "detection", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-ccp-std-11290"), productId: PRODUCTS.ccPlatesAurora, targetType: "standard", targetId: STANDARDS.iso11290, role: "conforms_to", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-ccp-ind-food"), productId: PRODUCTS.ccPlatesAurora, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-ccp-smp-milk"), productId: PRODUCTS.ccPlatesAurora, targetType: "sample_type", targetId: SAMPLE_TYPES.milk, role: "sample_type", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-ccp-inc"), productId: PRODUCTS.ccPlatesAurora, targetType: "incubation_condition", targetId: INCUBATION.aerobic3035, role: "incubation", evidence: e(SOURCES.auroraCatalogue, "source_captured", 0.75) },
    // SteriTest ST-200 (Condor) — closed sterility testing system.
    { ...ctx.canonical("edge-st200-app-sterility"), productId: PRODUCTS.st200Condor, targetType: "application", targetId: APPLICATIONS.sterilityTesting, role: "intended_use", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-st200-std-usp71"), productId: PRODUCTS.st200Condor, targetType: "standard", targetId: STANDARDS.usp71, role: "conforms_to", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-st200-mth-membrane"), productId: PRODUCTS.st200Condor, targetType: "method", targetId: METHODS.membraneFiltration, role: "method", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-st200-tt-sterility"), productId: PRODUCTS.st200Condor, targetType: "test_type", targetId: TEST_TYPES.sterilityTest, role: "test_type", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-st200-ind-pharma"), productId: PRODUCTS.st200Condor, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.85) },
    // SteriPump SP-3000 (Meridian) — competing closed system, thinner evidence.
    { ...ctx.canonical("edge-sp3000-app-sterility"), productId: PRODUCTS.sp3000Meridian, targetType: "application", targetId: APPLICATIONS.sterilityTesting, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-sp3000-std-usp71"), productId: PRODUCTS.sp3000Meridian, targetType: "standard", targetId: STANDARDS.usp71, role: "conforms_to", evidence: e(SOURCES.meridianCatalogue, "unverified", 0.5) },
    { ...ctx.canonical("edge-sp3000-mth-membrane"), productId: PRODUCTS.sp3000Meridian, targetType: "method", targetId: METHODS.membraneFiltration, role: "method", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-sp3000-ind-pharma"), productId: PRODUCTS.sp3000Meridian, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    // AirGuard AG-90 (Meridian) — open-plate air sampler (90 mm plates, not contact plates).
    { ...ctx.canonical("edge-ag90-app-em"), productId: PRODUCTS.ag90Meridian, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-ag90-smp-air"), productId: PRODUCTS.ag90Meridian, targetType: "sample_type", targetId: SAMPLE_TYPES.air, role: "sample_type", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-ag90-tt-bioburden"), productId: PRODUCTS.ag90Meridian, targetType: "test_type", targetId: TEST_TYPES.bioburden, role: "test_type", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-ag90-ind-pharma"), productId: PRODUCTS.ag90Meridian, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-ag90-ind-food"), productId: PRODUCTS.ag90Meridian, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.75) },
    // PartiCount PC-90 (Meridian)
    { ...ctx.canonical("edge-pc90-app-em"), productId: PRODUCTS.pc90Meridian, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-pc90-smp-air"), productId: PRODUCTS.pc90Meridian, targetType: "sample_type", targetId: SAMPLE_TYPES.air, role: "sample_type", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-pc90-ind-pharma"), productId: PRODUCTS.pc90Meridian, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    // DeltaSeed spore strips (DeltaBio) — steam sterilization validation.
    { ...ctx.canonical("edge-bigst-app-sterilval"), productId: PRODUCTS.biDelta, targetType: "application", targetId: APPLICATIONS.sterilizationValidation, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-bigst-orgm-gstearo"), productId: PRODUCTS.biDelta, targetType: "organism", targetId: ORGANISMS.gstearo, role: "biological_indicator", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.95) },
    { ...ctx.canonical("edge-bigst-std-11138"), productId: PRODUCTS.biDelta, targetType: "standard", targetId: STANDARDS.iso11138, role: "conforms_to", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-bigst-ind-pharma"), productId: PRODUCTS.biDelta, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    // SteriSure BI ampoules (Meridian) — ISO 11138 conformance not yet evidenced.
    { ...ctx.canonical("edge-biamp-app-sterilval"), productId: PRODUCTS.biSteriSure, targetType: "application", targetId: APPLICATIONS.sterilizationValidation, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-biamp-orgm-gstearo"), productId: PRODUCTS.biSteriSure, targetType: "organism", targetId: ORGANISMS.gstearo, role: "biological_indicator", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-biamp-std-11138"), productId: PRODUCTS.biSteriSure, targetType: "standard", targetId: STANDARDS.iso11138, role: "conforms_to", evidence: e(SOURCES.meridianCatalogue, "unverified", 0.5) },
    { ...ctx.canonical("edge-biamp-ind-pharma"), productId: PRODUCTS.biSteriSure, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    // -- Upstream: cell culture media --------------------------------------------
    { ...ctx.canonical("edge-chomax-app-upstream"), productId: PRODUCTS.choMaxNovara, targetType: "application", targetId: APPLICATIONS.upstreamCellCulture, role: "intended_use", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-chomax-ind-pharma"), productId: PRODUCTS.choMaxNovara, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-chomax-smp-broth"), productId: PRODUCTS.choMaxNovara, targetType: "sample_type", targetId: SAMPLE_TYPES.cellCultureBroth, role: "sample_type", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-feed-app-upstream"), productId: PRODUCTS.feedDelta, targetType: "application", targetId: APPLICATIONS.upstreamCellCulture, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-feed-ind-pharma"), productId: PRODUCTS.feedDelta, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    // -- Upstream: process chemicals ------------------------------------------------
    { ...ctx.canonical("edge-etoh-app-api"), productId: PRODUCTS.etohVesta, targetType: "application", targetId: APPLICATIONS.apiSynthesis, role: "intended_use", evidence: e(SOURCES.vestaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-etoh-ind-pharma"), productId: PRODUCTS.etohVesta, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.vestaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-pbs-app-upstream"), productId: PRODUCTS.pbsNovara, targetType: "application", targetId: APPLICATIONS.upstreamCellCulture, role: "intended_use", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-pbs-app-downstream"), productId: PRODUCTS.pbsNovara, targetType: "application", targetId: APPLICATIONS.downstreamPurification, role: "intended_use", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-pbs-ind-pharma"), productId: PRODUCTS.pbsNovara, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.novaraCatalogue, "source_captured", 0.8) },
    // -- Downstream: chromatography ---------------------------------------------------
    { ...ctx.canonical("edge-proa-app-downstream"), productId: PRODUCTS.proaAuriga, targetType: "application", targetId: APPLICATIONS.downstreamPurification, role: "intended_use", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-proa-mth-affinity"), productId: PRODUCTS.proaAuriga, targetType: "method", targetId: METHODS.affinityChromatography, role: "method", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-proa-smp-broth"), productId: PRODUCTS.proaAuriga, targetType: "sample_type", targetId: SAMPLE_TYPES.cellCultureBroth, role: "sample_type", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-proa-ind-pharma"), productId: PRODUCTS.proaAuriga, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-qmem-app-downstream"), productId: PRODUCTS.qKestrel, targetType: "application", targetId: APPLICATIONS.downstreamPurification, role: "intended_use", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-qmem-ind-pharma"), productId: PRODUCTS.qKestrel, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.8) },
    // -- Downstream: filtration ----------------------------------------------------------
    { ...ctx.canonical("edge-steriflow-app-sterilefil"), productId: PRODUCTS.steriFlowKestrel, targetType: "application", targetId: APPLICATIONS.sterileFiltration, role: "intended_use", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-steriflow-mth-membrane"), productId: PRODUCTS.steriFlowKestrel, targetType: "method", targetId: METHODS.membraneFiltration, role: "method", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-steriflow-smp-bulk"), productId: PRODUCTS.steriFlowKestrel, targetType: "sample_type", targetId: SAMPLE_TYPES.bulkDrugSubstance, role: "sample_type", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-steriflow-ind-pharma"), productId: PRODUCTS.steriFlowKestrel, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.kestrelCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tff-app-downstream"), productId: PRODUCTS.tffAuriga, targetType: "application", targetId: APPLICATIONS.downstreamPurification, role: "intended_use", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-tff-smp-bulk"), productId: PRODUCTS.tffAuriga, targetType: "sample_type", targetId: SAMPLE_TYPES.bulkDrugSubstance, role: "sample_type", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-tff-ind-pharma"), productId: PRODUCTS.tffAuriga, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.aurigaCatalogue, "source_captured", 0.8) },
    // -- QC: endotoxin testing --------------------------------------------------------------
    { ...ctx.canonical("edge-endozyme-app-endo"), productId: PRODUCTS.endoZymeOrizon, targetType: "application", targetId: APPLICATIONS.endotoxinTesting, role: "intended_use", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-endozyme-tt-endo"), productId: PRODUCTS.endoZymeOrizon, targetType: "test_type", targetId: TEST_TYPES.endotoxinTest, role: "test_type", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-endozyme-std-usp85"), productId: PRODUCTS.endoZymeOrizon, targetType: "standard", targetId: STANDARDS.usp85, role: "conforms_to", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-endozyme-ind-pharma"), productId: PRODUCTS.endoZymeOrizon, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-lal-app-endo"), productId: PRODUCTS.lalDelta, targetType: "application", targetId: APPLICATIONS.endotoxinTesting, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-lal-tt-endo"), productId: PRODUCTS.lalDelta, targetType: "test_type", targetId: TEST_TYPES.endotoxinTest, role: "test_type", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-lal-std-usp85"), productId: PRODUCTS.lalDelta, targetType: "standard", targetId: STANDARDS.usp85, role: "conforms_to", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-lal-smp-bulk"), productId: PRODUCTS.lalDelta, targetType: "sample_type", targetId: SAMPLE_TYPES.bulkDrugSubstance, role: "sample_type", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-lal-ind-pharma"), productId: PRODUCTS.lalDelta, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    // SteriPump closed canisters (Meridian)
    { ...ctx.canonical("edge-spcan-app-sterility"), productId: PRODUCTS.spCanMeridian, targetType: "application", targetId: APPLICATIONS.sterilityTesting, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-spcan-std-usp71"), productId: PRODUCTS.spCanMeridian, targetType: "standard", targetId: STANDARDS.usp71, role: "conforms_to", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-spcan-mth-membrane"), productId: PRODUCTS.spCanMeridian, targetType: "method", targetId: METHODS.membraneFiltration, role: "method", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-spcan-ind-pharma"), productId: PRODUCTS.spCanMeridian, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.8) },
    // DeltaPlate contact plates (DeltaBio)
    { ...ctx.canonical("edge-dcp-app-em"), productId: PRODUCTS.dcpDelta, targetType: "application", targetId: APPLICATIONS.envMonitoring, role: "intended_use", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-dcp-smp-surface"), productId: PRODUCTS.dcpDelta, targetType: "sample_type", targetId: SAMPLE_TYPES.surface, role: "sample_type", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.85) },
    { ...ctx.canonical("edge-dcp-tt-bioburden"), productId: PRODUCTS.dcpDelta, targetType: "test_type", targetId: TEST_TYPES.bioburden, role: "test_type", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-dcp-std-11133"), productId: PRODUCTS.dcpDelta, targetType: "standard", targetId: STANDARDS.iso11133, role: "conforms_to", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.8) },
    { ...ctx.canonical("edge-dcp-inc"), productId: PRODUCTS.dcpDelta, targetType: "incubation_condition", targetId: INCUBATION.aerobic3035, role: "incubation", evidence: e(SOURCES.deltaCatalogue, "source_captured", 0.75) },
    // OrizonQC E. coli pellets (Orizon)
    { ...ctx.canonical("edge-qcecoli-orgm"), productId: PRODUCTS.qcEcoliOrizon, targetType: "organism", targetId: ORGANISMS.ecoli, role: "qc_test_strain", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.95) },
    { ...ctx.canonical("edge-qcecoli-app-gpt"), productId: PRODUCTS.qcEcoliOrizon, targetType: "application", targetId: APPLICATIONS.growthPromotion, role: "intended_use", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.9) },
    { ...ctx.canonical("edge-qcecoli-std-11133"), productId: PRODUCTS.qcEcoliOrizon, targetType: "standard", targetId: STANDARDS.iso11133, role: "supports", evidence: e(SOURCES.orizonCatalogue, "source_captured", 0.75) },
    // Turntable + loops (accessories — intentionally thin evidence)
    { ...ctx.canonical("edge-turntable-ind-pharma"), productId: PRODUCTS.turntableCondor, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.condorCatalogue, "source_captured", 0.7) },
    { ...ctx.canonical("edge-loops-app-limits"), productId: PRODUCTS.loopsMeridian, targetType: "application", targetId: APPLICATIONS.microbialLimits, role: "intended_use", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.75) },
    { ...ctx.canonical("edge-loops-ind-pharma"), productId: PRODUCTS.loopsMeridian, targetType: "industry", targetId: INDUSTRIES.pharma, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.7) },
    { ...ctx.canonical("edge-loops-ind-food"), productId: PRODUCTS.loopsMeridian, targetType: "industry", targetId: INDUSTRIES.food, role: "target_industry", evidence: e(SOURCES.meridianCatalogue, "source_captured", 0.7) },
  ];

  return {
    brand: brands,
    product_family: productFamilies,
    product: products,
    product_format: productFormats,
    sku: skus,
    pack_configuration: packConfigurations,
    product_document: productDocuments,
    application: applications,
    method: methods,
    standard: standards,
    standard_version: standardVersions,
    organism: organisms,
    sample_type: sampleTypes,
    industry: industries,
    test_type: testTypes,
    incubation_condition: incubationConditions,
    preparation_method: preparationMethods,
    product_edge: productEdges,
  };
}
